"""
KariyerKoçu - TTS Service (Text-to-Speech)
==========================================
Edge-TTS kullanarak metin okuma servisi.
Teknik terimler için telaffuz sözlüğü içerir.
"""

import edge_tts
import asyncio
import re
import os
import tempfile
from typing import Optional


# Türkçe sesler
VOICES = {
    "male": "tr-TR-AhmetNeural",
    "female": "tr-TR-EmelNeural",
}

# 🔤 TEKNİK TERİM TELAFFUZ SÖZLÜĞÜ
# Türkçe ses için İngilizce kelimelerin fonetik yazımları
PRONUNCIATION_DICT = {
    # Programlama Dilleri
    "python": "Paytın",
    "Python": "Paytın",
    "javascript": "Cava Skript",
    "JavaScript": "Cava Skript",
    "typescript": "Tayp Skript",
    "TypeScript": "Tayp Skript",
    "java": "Cava",
    "Java": "Cava",
    "c++": "Si Plas Plas",
    "C++": "Si Plas Plas",
    "c#": "Si Şarp",
    "C#": "Si Şarp",
    "golang": "Go Lang",
    "rust": "Rast",
    "Rust": "Rast",
    "swift": "Svift",
    "Swift": "Svift",
    "kotlin": "Kotlın",
    "Kotlin": "Kotlın",
    
    # Framework & Kütüphaneler
    "react": "Riekt",
    "React": "Riekt",
    "angular": "Engyulır",
    "Angular": "Engyulır",
    "vue": "Vyu",
    "Vue": "Vyu",
    "nextjs": "Nekst Cey Es",
    "Next.js": "Nekst Cey Es",
    "node": "Nod",
    "Node": "Nod",
    "nodejs": "Nod Cey Es",
    "Node.js": "Nod Cey Es",
    "express": "Ekspres",
    "Express": "Ekspres",
    "fastapi": "Fast Ey Pi Ay",
    "FastAPI": "Fast Ey Pi Ay",
    "django": "Cengo",
    "Django": "Cengo",
    "flask": "Fılesk",
    "Flask": "Fılesk",
    "tensorflow": "Tensır Flov",
    "TensorFlow": "Tensır Flov",
    "pytorch": "Pay Torç",
    "PyTorch": "Pay Torç",
    
    # Veritabanı
    "sql": "Es Kyu El",
    "SQL": "Es Kyu El",
    "mysql": "May Es Kyu El",
    "MySQL": "May Es Kyu El",
    "postgresql": "Post Gres Kyu El",
    "PostgreSQL": "Post Gres Kyu El",
    "mongodb": "Mongo Di Bi",
    "MongoDB": "Mongo Di Bi",
    "redis": "Redis",
    "Redis": "Redis",
    "elasticsearch": "Elastik Sörç",
    "Elasticsearch": "Elastik Sörç",
    
    # DevOps & Araçlar
    "docker": "Dokır",
    "Docker": "Dokır",
    "kubernetes": "Kubernitis",
    "Kubernetes": "Kubernitis",
    "k8s": "Key Eyts",
    "git": "Git",
    "Git": "Git",
    "github": "Git Hab",
    "GitHub": "Git Hab",
    "gitlab": "Git Leb",
    "GitLab": "Git Leb",
    "jenkins": "Cenkins",
    "Jenkins": "Cenkins",
    "aws": "Ey Dablyu Es",
    "AWS": "Ey Dablyu Es",
    "azure": "Ejır",
    "Azure": "Ejır",
    "gcp": "Ci Si Pi",
    "GCP": "Ci Si Pi",
    "linux": "Linuks",
    "Linux": "Linuks",
    "nginx": "Encinks",
    "Nginx": "Encinks",
    
    # Kavramlar
    "api": "Ey Pi Ay",
    "API": "Ey Pi Ay",
    "rest": "Rest",
    "REST": "Rest",
    "restful": "Rest Ful",
    "RESTful": "Rest Ful",
    "graphql": "Graf Kyu El",
    "GraphQL": "Graf Kyu El",
    "websocket": "Veb Soket",
    "WebSocket": "Veb Soket",
    "microservices": "Maykro Servisler",
    "backend": "Bek End",
    "Backend": "Bek End",
    "frontend": "Front End",
    "Frontend": "Front End",
    "fullstack": "Ful Stek",
    "Fullstack": "Ful Stek",
    "devops": "Dev Ops",
    "DevOps": "Dev Ops",
    "agile": "Ecayl",
    "Agile": "Ecayl",
    "scrum": "Skram",
    "Scrum": "Skram",
    "ci/cd": "Si Ay Si Di",
    "CI/CD": "Si Ay Si Di",
    
    # AI/ML
    "machine learning": "Meşin Lörning",
    "Machine Learning": "Meşin Lörning",
    "deep learning": "Dip Lörning",
    "Deep Learning": "Dip Lörning",
    "deepfake": "Dipfeyk",
    "Deepfake": "Dipfeyk",
    "deepfakes": "Dipfeyks",
    "Deepfakes": "Dipfeyks",
    "neural network": "Nöral Netvörk",
    "transformer": "Transformır",
    "llm": "El El Em",
    "LLM": "El El Em",
    "gpt": "Ci Pi Ti",
    "GPT": "Ci Pi Ti",
    "openai": "Opın Ey Ay",
    "OpenAI": "Opın Ey Ay",
    "chatgpt": "Çet Ci Pi Ti",
    "ChatGPT": "Çet Ci Pi Ti",
    "yolo": "Yolo",
    "YOLO": "Yolo",
    "cnn": "Si En En",
    "CNN": "Si En En",
    "nlp": "En El Pi",
    "NLP": "En El Pi",
    "computer vision": "Kompyutır Vijın",
    "Computer Vision": "Kompyutır Vijın",
    "opencv": "Opın Si Vi",
    "OpenCV": "Opın Si Vi",
    "huggingface": "Haging Feys",
    "Huggingface": "Haging Feys",
    "HuggingFace": "Haging Feys",
    "stable diffusion": "Steybıl Difüjın",
    "Stable Diffusion": "Steybıl Difüjın",
    "midjourney": "Mid Cörni",
    "Midjourney": "Mid Cörni",
    "dall-e": "Dal İ",
    "DALL-E": "Dal İ",
    
    # Donanım
    "jetson": "Cetsın",
    "Jetson": "Cetsın",
    "raspberry": "Razberi",
    "Raspberry": "Razberi",
    "nvidia": "Envidya",
    "NVIDIA": "Envidya",
    "cuda": "Kuda",
    "CUDA": "Kuda",
    "arm": "Arm",
    "ARM": "Arm",
    
    # Oyun Geliştirme
    "unreal engine": "Anril Encin",
    "Unreal Engine": "Anril Encin",
    "unity": "Yuniti",
    "Unity": "Yuniti",
    "blueprint": "Blupırint",
    "Blueprint": "Blupırint",
    "blueprints": "Blupırints",
    "Blueprints": "Blupırints",
    "game engine": "Geym Encin",
    "Game Engine": "Geym Encin",
    "shader": "Şeydır",
    "Shader": "Şeydır",
    "shaders": "Şeydırs",
    "physics engine": "Fiziks Encin",
    "ray tracing": "Rey Treysing",
    "Ray Tracing": "Rey Treysing",
    "mesh": "Meş",
    "Mesh": "Meş",
    "texture": "Tekstür",
    "Texture": "Tekstür",
    "rendering": "Rendıring",
    "Rendering": "Rendıring",
    "asset": "Eset",
    "Asset": "Eset",
    "assets": "Esets",
    "Assets": "Esets",
    "viewport": "Vyuport",
    "Viewport": "Vyuport",
    "gameplay": "Geymplay",
    "Gameplay": "Geymplay",
    
    # Diğer
    "decorator": "Dekoratör",
    "async": "Eysink",
    "await": "Eveyt",
    "callback": "Kolbek",
    "middleware": "Midılver",
    "framework": "Freymvörk",
    "library": "Laybreri",
    "dependency": "Dipendınsi",
    "repository": "Repozitori",
    "branch": "Branç",
    "merge": "Mörc",
    "commit": "Komit",
    "push": "Puş",
    "pull": "Pul",
    "deploy": "Diploy",
    "interface": "İnterfeys",
    "inheritance": "İnheritıns",
    "polymorphism": "Polimorfizm",
    "encapsulation": "Enkapsüleşın",
    "abstraction": "Abstrakşın",
    "container": "Konteyner",
    "image": "İmıc",
    "testing": "Testing",
    "debugging": "Dibagging",
    "pipeline": "Paypılayn",
    
    # Mülakat soruları için ek kelimeler
    "over": "Ovır",
    "overview": "Ovırvyu",
    "experience": "Ekspiriyıns",
    "project": "Procekt",
    "projects": "Procekts",
    "challenge": "Çelınc",
    "challenges": "Çelıncız",
    "solution": "Solüşın",
    "solutions": "Solüşıns",
    "problem": "Prablım",
    "problems": "Prablıms",
    "example": "Egzampıl",
    "examples": "Egzampıls",
    "question": "Kuesçın",
    "questions": "Kuesçıns",
    "answer": "Ansır",
    "describe": "Diskrayb",
    "explain": "Ekspleyn",
    "implement": "İmpliment",
    "implementation": "İmplimenteyşın",
    "function": "Fankşın",
    "functions": "Fankşıns",
    "method": "Metıd",
    "methods": "Metıds",
    "class": "Klas",
    "classes": "Klasız",
    "object": "Obcekt",
    "objects": "Obcekts",
    "variable": "Veriyıbıl",
    "variables": "Veriyıbıls",
    "algorithm": "Algırıdım",
    "algorithms": "Algırıdıms",
    "data structure": "Deytı Strakçır",
    "data structures": "Deytı Strakçırs",
    "database": "Deytıbeys",
    "performance": "Pörformıns",
    "optimize": "Optimayz",
    "optimization": "Optimizeyşın",
    "scalable": "Skeylıbıl",
    "scalability": "Skeylıbiliti",
    "architecture": "Arkitekçır",
    "design pattern": "Dizayn Patırn",
    "design patterns": "Dizayn Patırns",
    "code review": "Kod Rivyu",
    "refactor": "Rifaktır",
    "refactoring": "Rifaktıring",
    "version control": "Vörcın Kontrol",
    "feature": "Fiçır",
    "features": "Fiçırs",
    "bug": "Bag",
    "bugs": "Bags",
    "fix": "Fiks",
    "issue": "İşu",
    "issues": "İşus",
    "task": "Task",
    "tasks": "Tasks",
    "sprint": "Sprint",
    "workflow": "Vörkflov",
    "requirement": "Rikuayırmınt",
    "requirements": "Rikuayırmınts",
    "specification": "Spesifikeyşın",
    "documentation": "Dakümınteyşın",
    "software": "Softvır",
    "hardware": "Hardvır",
    "network": "Netvörk",
    "server": "Sörvır",
    "client": "Klayınt",
    "user": "Yuzır",
    "developer": "Divelopır",
    "engineer": "Enciinır",
    "manager": "Menıcır",
    "team": "Tim",
    "agile": "Ecayl",
    "kanban": "Kanban",
    "jira": "Cirı",
    "slack": "Slek",
    "zoom": "Zum",
    
    # ============================================
    # YAPAY ZEKA & MAKİNE ÖĞRENMESİ (Genişletilmiş)
    # ============================================
    "rnn": "Ar En En",
    "RNN": "Ar En En",
    "lstm": "El Es Ti Em",
    "LSTM": "El Es Ti Em",
    "gru": "Ci Ar Yu",
    "GRU": "Ci Ar Yu",
    "gan": "Gen",
    "GAN": "Gen",
    "gans": "Gens",
    "GANs": "Gens",
    "vae": "Vi Ey İ",
    "VAE": "Vi Ey İ",
    "autoencoder": "Oto Enkodır",
    "Autoencoder": "Oto Enkodır",
    "encoder": "Enkodır",
    "Encoder": "Enkodır",
    "decoder": "Dikodır",
    "Decoder": "Dikodır",
    "attention": "Atenşın",
    "Attention": "Atenşın",
    "self-attention": "Self Atenşın",
    "multi-head attention": "Malti Hed Atenşın",
    "bert": "Bört",
    "BERT": "Bört",
    "roberta": "Robörta",
    "RoBERTa": "Robörta",
    "xlnet": "Eks El Net",
    "XLNet": "Eks El Net",
    "t5": "Ti Fayv",
    "T5": "Ti Fayv",
    "gpt-4": "Ci Pi Ti For",
    "GPT-4": "Ci Pi Ti For",
    "gpt-3": "Ci Pi Ti Tri",
    "GPT-3": "Ci Pi Ti Tri",
    "gemini": "Cemini",
    "Gemini": "Cemini",
    "claude": "Klod",
    "Claude": "Klod",
    "anthropic": "Antropik",
    "Anthropic": "Antropik",
    "mistral": "Mistral",
    "Mistral": "Mistral",
    "llama": "Lama",
    "LLaMA": "Lama",
    "embedding": "Embeding",
    "embeddings": "Embeddings",
    "Embedding": "Embeding",
    "vector": "Vektör",
    "Vector": "Vektör",
    "vectors": "Vektörs",
    "tokenizer": "Tokınayzer",
    "Tokenizer": "Tokınayzer",
    "tokenization": "Tokinizeyşın",
    "token": "Tokın",
    "tokens": "Tokıns",
    "fine-tuning": "Fayn Tyuning",
    "fine tuning": "Fayn Tyuning",
    "Fine-Tuning": "Fayn Tyuning",
    "pre-training": "Pri Treyning",
    "pretraining": "Pri Treyning",
    "transfer learning": "Transfer Lörning",
    "Transfer Learning": "Transfer Lörning",
    "reinforcement learning": "Rinforsment Lörning",
    "Reinforcement Learning": "Rinforsment Lörning",
    "supervised learning": "Süpırvayzd Lörning",
    "Supervised Learning": "Süpırvayzd Lörning",
    "unsupervised learning": "Ansüpırvayzd Lörning",
    "Unsupervised Learning": "Ansüpırvayzd Lörning",
    "semi-supervised": "Semi Süpırvayzd",
    "classification": "Klasifikeyşın",
    "Classification": "Klasifikeyşın",
    "regression": "Regresyın",
    "Regression": "Regresyın",
    "clustering": "Klastıring",
    "Clustering": "Klastıring",
    "segmentation": "Segmenteyşın",
    "Segmentation": "Segmenteyşın",
    "detection": "Detekşın",
    "Detection": "Detekşın",
    "recognition": "Rekognişın",
    "Recognition": "Rekognişın",
    "inference": "İnfırıns",
    "Inference": "İnfırıns",
    "training": "Treyning",
    "Training": "Treyning",
    "validation": "Valideyşın",
    "Validation": "Valideyşın",
    "test set": "Test Set",
    "train set": "Treyn Set",
    "overfitting": "Ovır Fiting",
    "Overfitting": "Ovır Fiting",
    "underfitting": "Andır Fiting",
    "Underfitting": "Andır Fiting",
    "regularization": "Regyularizeyşın",
    "Regularization": "Regyularizeyşın",
    "dropout": "Dropavt",
    "Dropout": "Dropavt",
    "batch normalization": "Beç Normalizeyşın",
    "Batch Normalization": "Beç Normalizeyşın",
    "layer normalization": "Leyr Normalizeyşın",
    "Layer Normalization": "Leyr Normalizeyşın",
    "activation function": "Aktiveyşın Fankşın",
    "relu": "Relu",
    "ReLU": "Relu",
    "sigmoid": "Sigmoid",
    "Sigmoid": "Sigmoid",
    "tanh": "Tenç",
    "softmax": "Softmeks",
    "Softmax": "Softmeks",
    "loss function": "Los Fankşın",
    "Loss Function": "Los Fankşın",
    "cross entropy": "Kros Entropi",
    "Cross Entropy": "Kros Entropi",
    "gradient": "Greydiyınt",
    "Gradient": "Greydiyınt",
    "gradient descent": "Greydiyınt Desent",
    "Gradient Descent": "Greydiyınt Desent",
    "backpropagation": "Bek Propageyşın",
    "Backpropagation": "Bek Propageyşın",
    "optimizer": "Optimayzır",
    "Optimizer": "Optimayzır",
    "adam": "Edem",
    "Adam": "Edem",
    "sgd": "Es Ci Di",
    "SGD": "Es Ci Di",
    "learning rate": "Lörning Reyt",
    "Learning Rate": "Lörning Reyt",
    "epoch": "İpok",
    "epochs": "İpoks",
    "Epoch": "İpok",
    "batch": "Beç",
    "Batch": "Beç",
    "batch size": "Beç Sayz",
    "mini-batch": "Mini Beç",
    "hyperparameter": "Haypır Paramitır",
    "Hyperparameter": "Haypır Paramitır",
    "hyperparameters": "Haypır Paramitırs",
    "feature": "Fiçır",
    "features": "Fiçırs",
    "feature extraction": "Fiçır Ekstrekşın",
    "Feature Extraction": "Fiçır Ekstrekşın",
    "feature engineering": "Fiçır Enciinıring",
    "Feature Engineering": "Fiçır Enciinıring",
    "dimensionality reduction": "Dimenjınaliti Ridakşın",
    "pca": "Pi Si Ey",
    "PCA": "Pi Si Ey",
    "t-sne": "Ti Sni",
    "t-SNE": "Ti Sni",
    "umap": "Yu Mep",
    "UMAP": "Yu Mep",
    "k-means": "Key Mins",
    "K-Means": "Key Mins",
    "kmeans": "Key Mins",
    "random forest": "Rendım Forest",
    "Random Forest": "Rendım Forest",
    "decision tree": "Disijın Tri",
    "Decision Tree": "Disijın Tri",
    "xgboost": "Eks Ci Bust",
    "XGBoost": "Eks Ci Bust",
    "lightgbm": "Layt Ci Bi Em",
    "LightGBM": "Layt Ci Bi Em",
    "catboost": "Ket Bust",
    "CatBoost": "Ket Bust",
    "svm": "Es Vi Em",
    "SVM": "Es Vi Em",
    "support vector machine": "Sapört Vektör Meşin",
    "Support Vector Machine": "Sapört Vektör Meşin",
    "naive bayes": "Neyiv Beyiz",
    "Naive Bayes": "Neyiv Beyiz",
    "logistic regression": "Locistik Regresyın",
    "Logistic Regression": "Locistik Regresyın",
    "linear regression": "Liniyır Regresyın",
    "Linear Regression": "Liniyır Regresyın",
    "knn": "Key En En",
    "KNN": "Key En En",
    "k-nearest neighbors": "Key Nirist Neybırs",
    "ensemble": "Ensembıl",
    "Ensemble": "Ensembıl",
    "boosting": "Busting",
    "Boosting": "Busting",
    "bagging": "Beging",
    "Bagging": "Beging",
    "stacking": "Steking",
    "Stacking": "Steking",
    "cross-validation": "Kros Valideyşın",
    "Cross-Validation": "Kros Valideyşın",
    "precision": "Prisijın",
    "Precision": "Prisijın",
    "recall": "Rikol",
    "Recall": "Rikol",
    "f1 score": "Ef Van Skor",
    "F1 Score": "Ef Van Skor",
    "accuracy": "Ekyurısi",
    "Accuracy": "Ekyurısi",
    "confusion matrix": "Konfüjın Metriks",
    "Confusion Matrix": "Konfüjın Metriks",
    "roc curve": "Rok Körv",
    "ROC Curve": "Rok Körv",
    "auc": "Ey Yu Si",
    "AUC": "Ey Yu Si",
    "mean squared error": "Min Skuerd Eror",
    "mse": "Em Es İ",
    "MSE": "Em Es İ",
    "rmse": "Ar Em Es İ",
    "RMSE": "Ar Em Es İ",
    "mae": "Em Ey İ",
    "MAE": "Em Ey İ",
    
    # ============================================
    # GÖRÜNTÜ İŞLEME & BİLGİSAYARLI GÖRÜ
    # ============================================
    "resnet": "Res Net",
    "ResNet": "Res Net",
    "vgg": "Vi Ci Ci",
    "VGG": "Vi Ci Ci",
    "alexnet": "Aleks Net",
    "AlexNet": "Aleks Net",
    "inception": "İnsepşın",
    "Inception": "İnsepşın",
    "efficientnet": "Efişınt Net",
    "EfficientNet": "Efişınt Net",
    "mobilenet": "Mobayıl Net",
    "MobileNet": "Mobayıl Net",
    "densenet": "Dens Net",
    "DenseNet": "Dens Net",
    "unet": "Yu Net",
    "U-Net": "Yu Net",
    "faster rcnn": "Fastır Ar Si En En",
    "Faster R-CNN": "Fastır Ar Si En En",
    "mask rcnn": "Mesk Ar Si En En",
    "Mask R-CNN": "Mesk Ar Si En En",
    "ssd": "Es Es Di",
    "SSD": "Es Es Di",
    "retinanet": "Retina Net",
    "RetinaNet": "Retina Net",
    "feature pyramid": "Fiçır Piramid",
    "Feature Pyramid": "Fiçır Piramid",
    "fpn": "Ef Pi En",
    "FPN": "Ef Pi En",
    "anchor box": "Enkır Boks",
    "bounding box": "Bavnding Boks",
    "Bounding Box": "Bavnding Boks",
    "iou": "Ay Ov Yu",
    "IoU": "Ay Ov Yu",
    "non-max suppression": "Non Meks Sapresyın",
    "nms": "En Em Es",
    "NMS": "En Em Es",
    "image augmentation": "İmıc Ogmenteyşın",
    "data augmentation": "Deytı Ogmenteyşın",
    "Data Augmentation": "Deytı Ogmenteyşın",
    "convolution": "Konvolüşın",
    "Convolution": "Konvolüşın",
    "convolutional": "Konvolüşınıl",
    "Convolutional": "Konvolüşınıl",
    "pooling": "Puling",
    "Pooling": "Puling",
    "max pooling": "Meks Puling",
    "Max Pooling": "Meks Puling",
    "average pooling": "Evrıc Puling",
    "stride": "Strayd",
    "Stride": "Strayd",
    "padding": "Peding",
    "Padding": "Peding",
    "kernel": "Körnıl",
    "Kernel": "Körnıl",
    "filter": "Filtır",
    "Filter": "Filtır",
    "channel": "Çenıl",
    "Channel": "Çenıl",
    "rgb": "Ar Ci Bi",
    "RGB": "Ar Ci Bi",
    "grayscale": "Grey Skeyl",
    "Grayscale": "Grey Skeyl",
    "histogram": "Histoğram",
    "Histogram": "Histoğram",
    "edge detection": "Ec Detekşın",
    "Edge Detection": "Ec Detekşın",
    "canny": "Keni",
    "Canny": "Keni",
    "sobel": "Sobel",
    "Sobel": "Sobel",
    "hough transform": "Haf Transform",
    "Hough Transform": "Haf Transform",
    "morphology": "Morfoloci",
    "Morphology": "Morfoloci",
    "erosion": "İrojın",
    "Erosion": "İrojın",
    "dilation": "Dayleyşın",
    "Dilation": "Dayleyşın",
    "contour": "Kontur",
    "Contour": "Kontur",
    "contours": "Konturs",
    "blob": "Blob",
    "Blob": "Blob",
    "keypoint": "Kipoynt",
    "Keypoint": "Kipoynt",
    "descriptor": "Deskriptır",
    "Descriptor": "Deskriptır",
    "sift": "Sift",
    "SIFT": "Sift",
    "surf": "Sörf",
    "SURF": "Sörf",
    "orb": "Orb",
    "ORB": "Orb",
    "harris corner": "Heris Kornır",
    "optical flow": "Optikal Flov",
    "Optical Flow": "Optikal Flov",
    "stereo vision": "Steriyo Vijın",
    "depth estimation": "Dept Estimeyşın",
    "Depth Estimation": "Dept Estimeyşın",
    "point cloud": "Poynt Klavd",
    "Point Cloud": "Poynt Klavd",
    "lidar": "Laydır",
    "LiDAR": "Laydır",
    "slam": "Slem",
    "SLAM": "Slem",
    "ocr": "Ov Si Ar",
    "OCR": "Ov Si Ar",
    "face detection": "Feys Detekşın",
    "Face Detection": "Feys Detekşın",
    "face recognition": "Feys Rekognişın",
    "Face Recognition": "Feys Rekognişın",
    "facial landmark": "Feyşıl Lendmark",
    "pose estimation": "Poz Estimeyşın",
    "Pose Estimation": "Poz Estimeyşın",
    "action recognition": "Ekşın Rekognişın",
    "Action Recognition": "Ekşın Rekognişın",
    "video analytics": "Vidyo Enalitiks",
    "Video Analytics": "Vidyo Enalitiks",
    
    # ============================================
    # DOĞAL DİL İŞLEME (NLP)
    # ============================================
    "natural language processing": "Neçırıl Lenguıc Prosesing",
    "Natural Language Processing": "Neçırıl Lenguıc Prosesing",
    "sentiment analysis": "Sentimınt Enalisis",
    "Sentiment Analysis": "Sentimınt Enalisis",
    "named entity recognition": "Neymd Entiti Rekognişın",
    "ner": "En İ Ar",
    "NER": "En İ Ar",
    "part of speech": "Part Ov Spiç",
    "pos tagging": "Pos Teging",
    "POS Tagging": "Pos Teging",
    "dependency parsing": "Dipendınsi Parsing",
    "Dependency Parsing": "Dipendınsi Parsing",
    "constituency parsing": "Konstityuınsi Parsing",
    "lemmatization": "Lematizeyşın",
    "Lemmatization": "Lematizeyşın",
    "stemming": "Steming",
    "Stemming": "Steming",
    "stopwords": "Stop Vörds",
    "Stopwords": "Stop Vörds",
    "bag of words": "Beg Ov Vörds",
    "Bag of Words": "Beg Ov Vörds",
    "bow": "Bov",
    "BoW": "Bov",
    "tf-idf": "Ti Ef Ay Di Ef",
    "TF-IDF": "Ti Ef Ay Di Ef",
    "word2vec": "Vörd Tu Vek",
    "Word2Vec": "Vörd Tu Vek",
    "glove": "Glov",
    "GloVe": "Glov",
    "fasttext": "Fast Tekst",
    "FastText": "Fast Tekst",
    "elmo": "Elmo",
    "ELMo": "Elmo",
    "language model": "Lenguıc Modıl",
    "Language Model": "Lenguıc Modıl",
    "seq2seq": "Sik Tu Sik",
    "Seq2Seq": "Sik Tu Sik",
    "sequence to sequence": "Sikuıns Tu Sikuıns",
    "machine translation": "Meşin Transleyşın",
    "Machine Translation": "Meşin Transleyşın",
    "text generation": "Tekst Cenerayşın",
    "Text Generation": "Tekst Cenerayşın",
    "text classification": "Tekst Klasifikeyşın",
    "Text Classification": "Tekst Klasifikeyşın",
    "text summarization": "Tekst Samırizeyşın",
    "Text Summarization": "Tekst Samırizeyşın",
    "question answering": "Kuesçın Ansıring",
    "Question Answering": "Kuesçın Ansıring",
    "qa": "Kyu Ey",
    "QA": "Kyu Ey",
    "chatbot": "Çetbot",
    "Chatbot": "Çetbot",
    "conversational ai": "Konvırseyşınıl Ey Ay",
    "Conversational AI": "Konvırseyşınıl Ey Ay",
    "dialogue system": "Dayılog Sistım",
    "Dialogue System": "Dayılog Sistım",
    "intent recognition": "İntent Rekognişın",
    "Intent Recognition": "İntent Rekognişın",
    "slot filling": "Slot Filing",
    "Slot Filling": "Slot Filing",
    "rag": "Reg",
    "RAG": "Reg",
    "retrieval augmented generation": "Ritrivıl Ogmentıd Cenerayşın",
    "Retrieval Augmented Generation": "Ritrivıl Ogmentıd Cenerayşın",
    "prompt engineering": "Prompt Enciinıring",
    "Prompt Engineering": "Prompt Enciinıring",
    "zero-shot": "Ziro Şat",
    "Zero-Shot": "Ziro Şat",
    "few-shot": "Fyu Şat",
    "Few-Shot": "Fyu Şat",
    "chain of thought": "Çeyn Ov Tot",
    "Chain of Thought": "Çeyn Ov Tot",
    "cot": "Kot",
    "CoT": "Kot",
    
    # ============================================
    # VERİ BİLİMİ & ANALİTİK
    # ============================================
    "data science": "Deytı Sayıns",
    "Data Science": "Deytı Sayıns",
    "data scientist": "Deytı Sayıntist",
    "Data Scientist": "Deytı Sayıntist",
    "data analyst": "Deytı Enalist",
    "Data Analyst": "Deytı Enalist",
    "data engineer": "Deytı Enciinır",
    "Data Engineer": "Deytı Enciinır",
    "big data": "Big Deytı",
    "Big Data": "Big Deytı",
    "data mining": "Deytı Mayning",
    "Data Mining": "Deytı Mayning",
    "data warehouse": "Deytı Verhavs",
    "Data Warehouse": "Deytı Verhavs",
    "data lake": "Deytı Leyk",
    "Data Lake": "Deytı Leyk",
    "etl": "İ Ti El",
    "ETL": "İ Ti El",
    "extract transform load": "Ekstrek Transform Lod",
    "Extract Transform Load": "Ekstrek Transform Lod",
    "elt": "İ El Ti",
    "ELT": "İ El Ti",
    "data pipeline": "Deytı Paypılayn",
    "Data Pipeline": "Deytı Paypılayn",
    "data ingestion": "Deytı İncesçın",
    "Data Ingestion": "Deytı İncesçın",
    "batch processing": "Beç Prosesing",
    "Batch Processing": "Beç Prosesing",
    "stream processing": "Strim Prosesing",
    "Stream Processing": "Strim Prosesing",
    "real-time": "Riıl Taym",
    "Real-Time": "Riıl Taym",
    "apache spark": "Epaçi Spark",
    "Apache Spark": "Epaçi Spark",
    "spark": "Spark",
    "Spark": "Spark",
    "pyspark": "Pay Spark",
    "PySpark": "Pay Spark",
    "hadoop": "Hadop",
    "Hadoop": "Hadop",
    "hdfs": "Eyç Di Ef Es",
    "HDFS": "Eyç Di Ef Es",
    "mapreduce": "Mep Ridüs",
    "MapReduce": "Mep Ridüs",
    "hive": "Hayv",
    "Hive": "Hayv",
    "pig": "Pig",
    "Pig": "Pig",
    "kafka": "Kafka",
    "Kafka": "Kafka",
    "apache kafka": "Epaçi Kafka",
    "Apache Kafka": "Epaçi Kafka",
    "flink": "Flink",
    "Flink": "Flink",
    "airflow": "Eyrflov",
    "Airflow": "Eyrflov",
    "apache airflow": "Epaçi Eyrflov",
    "Apache Airflow": "Epaçi Eyrflov",
    "dag": "Deg",
    "DAG": "Deg",
    "dags": "Degs",
    "DAGs": "Degs",
    "pandas": "Pandas",
    "Pandas": "Pandas",
    "numpy": "Nampay",
    "NumPy": "Nampay",
    "scipy": "Say Pay",
    "SciPy": "Say Pay",
    "matplotlib": "Metplat Lib",
    "Matplotlib": "Metplat Lib",
    "seaborn": "Siborn",
    "Seaborn": "Siborn",
    "plotly": "Platli",
    "Plotly": "Platli",
    "bokeh": "Boke",
    "Bokeh": "Boke",
    "tableau": "Tablo",
    "Tableau": "Tablo",
    "power bi": "Pavır Bi Ay",
    "Power BI": "Pavır Bi Ay",
    "looker": "Lukır",
    "Looker": "Lukır",
    "metabase": "Metıbeys",
    "Metabase": "Metıbeys",
    "superset": "Süpırset",
    "Superset": "Süpırset",
    "jupyter": "Cupitır",
    "Jupyter": "Cupitır",
    "jupyter notebook": "Cupitır Notbuk",
    "Jupyter Notebook": "Cupitır Notbuk",
    "jupyterlab": "Cupitır Leb",
    "JupyterLab": "Cupitır Leb",
    "colab": "Kolab",
    "Colab": "Kolab",
    "google colab": "Gugıl Kolab",
    "Google Colab": "Gugıl Kolab",
    "kaggle": "Kagıl",
    "Kaggle": "Kagıl",
    "dataset": "Deytıset",
    "Dataset": "Deytıset",
    "dataframe": "Deytıfreym",
    "DataFrame": "Deytıfreym",
    "series": "Siris",
    "Series": "Siris",
    "index": "İndeks",
    "Index": "İndeks",
    "column": "Kolum",
    "Column": "Kolum",
    "row": "Rov",
    "Row": "Rov",
    "null": "Nal",
    "Null": "Nal",
    "nan": "Nen",
    "NaN": "Nen",
    "missing value": "Mising Velyu",
    "Missing Value": "Mising Velyu",
    "outlier": "Avtlayır",
    "Outlier": "Avtlayır",
    "outliers": "Avtlayırs",
    "normalization": "Normalizeyşın",
    "Normalization": "Normalizeyşın",
    "standardization": "Stendırdizeyşın",
    "Standardization": "Stendırdizeyşın",
    "scaling": "Skeyling",
    "Scaling": "Skeyling",
    "min-max": "Min Meks",
    "Min-Max": "Min Meks",
    "z-score": "Zi Skor",
    "Z-Score": "Zi Skor",
    "correlation": "Korelayşın",
    "Correlation": "Korelayşın",
    "covariance": "Kovariyans",
    "Covariance": "Kovariyans",
    "distribution": "Distribüşın",
    "Distribution": "Distribüşın",
    "normal distribution": "Normal Distribüşın",
    "gaussian": "Gausiyın",
    "Gaussian": "Gausiyın",
    "mean": "Min",
    "Mean": "Min",
    "median": "Mediyın",
    "Median": "Mediyın",
    "mode": "Mod",
    "Mode": "Mod",
    "variance": "Variyans",
    "Variance": "Variyans",
    "standard deviation": "Stendırt Diviyeyşın",
    "Standard Deviation": "Stendırt Diviyeyşın",
    "percentile": "Pörsentayl",
    "Percentile": "Pörsentayl",
    "quartile": "Kuartayl",
    "Quartile": "Kuartayl",
    "iqr": "Ay Kyu Ar",
    "IQR": "Ay Kyu Ar",
    "hypothesis testing": "Haypotesis Testing",
    "Hypothesis Testing": "Haypotesis Testing",
    "p-value": "Pi Velyu",
    "P-Value": "Pi Velyu",
    "confidence interval": "Konfidıns İntırvıl",
    "Confidence Interval": "Konfidıns İntırvıl",
    "a/b testing": "Ey Bi Testing",
    "A/B Testing": "Ey Bi Testing",
    
    # ============================================
    # YAZILIM GELİŞTİRME & MİMARİ
    # ============================================
    "solid": "Solid",
    "SOLID": "Solid",
    "single responsibility": "Singıl Risponsibiliti",
    "Single Responsibility": "Singıl Risponsibiliti",
    "open closed": "Opın Klosd",
    "Open Closed": "Opın Klosd",
    "liskov substitution": "Liskov Sabstitüşın",
    "Liskov Substitution": "Liskov Sabstitüşın",
    "interface segregation": "İnterfeys Segregeyşın",
    "Interface Segregation": "İnterfeys Segregeyşın",
    "dependency inversion": "Dipendınsi İnvörsın",
    "Dependency Inversion": "Dipendınsi İnvörsın",
    "dry": "Dray",
    "DRY": "Dray",
    "kiss": "Kis",
    "KISS": "Kis",
    "yagni": "Yagni",
    "YAGNI": "Yagni",
    "singleton": "Singıltın",
    "Singleton": "Singıltın",
    "factory": "Fektıri",
    "Factory": "Fektıri",
    "factory pattern": "Fektıri Patırn",
    "Factory Pattern": "Fektıri Patırn",
    "abstract factory": "Ebstrekt Fektıri",
    "Abstract Factory": "Ebstrekt Fektıri",
    "builder": "Bildır",
    "Builder": "Bildır",
    "builder pattern": "Bildır Patırn",
    "Builder Pattern": "Bildır Patırn",
    "prototype": "Prototayp",
    "Prototype": "Prototayp",
    "adapter": "Edaptır",
    "Adapter": "Edaptır",
    "adapter pattern": "Edaptır Patırn",
    "Adapter Pattern": "Edaptır Patırn",
    "bridge": "Bric",
    "Bridge": "Bric",
    "composite": "Kompozit",
    "Composite": "Kompozit",
    "facade": "Fesad",
    "Facade": "Fesad",
    "flyweight": "Flayveyt",
    "Flyweight": "Flayveyt",
    "proxy": "Proksi",
    "Proxy": "Proksi",
    "proxy pattern": "Proksi Patırn",
    "Proxy Pattern": "Proksi Patırn",
    "chain of responsibility": "Çeyn Ov Risponsibiliti",
    "Chain of Responsibility": "Çeyn Ov Risponsibiliti",
    "command": "Komend",
    "Command": "Komend",
    "command pattern": "Komend Patırn",
    "Command Pattern": "Komend Patırn",
    "interpreter": "İntörpritır",
    "Interpreter": "İntörpritır",
    "iterator": "İtıreytır",
    "Iterator": "İtıreytır",
    "mediator": "Midiyeytır",
    "Mediator": "Midiyeytır",
    "memento": "Memento",
    "Memento": "Memento",
    "observer": "Obsörvır",
    "Observer": "Obsörvır",
    "observer pattern": "Obsörvır Patırn",
    "Observer Pattern": "Obsörvır Patırn",
    "state": "Steyt",
    "State": "Steyt",
    "state pattern": "Steyt Patırn",
    "State Pattern": "Steyt Patırn",
    "strategy": "Stretıci",
    "Strategy": "Stretıci",
    "strategy pattern": "Stretıci Patırn",
    "Strategy Pattern": "Stretıci Patırn",
    "template method": "Templıt Metıd",
    "Template Method": "Templıt Metıd",
    "visitor": "Vizitır",
    "Visitor": "Vizitır",
    "mvc": "Em Vi Si",
    "MVC": "Em Vi Si",
    "model view controller": "Modıl Vyu Kontrolır",
    "Model View Controller": "Modıl Vyu Kontrolır",
    "mvvm": "Em Vi Vi Em",
    "MVVM": "Em Vi Vi Em",
    "mvp": "Em Vi Pi",
    "MVP": "Em Vi Pi",
    "clean architecture": "Klin Arkitekçır",
    "Clean Architecture": "Klin Arkitekçır",
    "hexagonal architecture": "Heksegonıl Arkitekçır",
    "Hexagonal Architecture": "Heksegonıl Arkitekçır",
    "onion architecture": "Anyın Arkitekçır",
    "Onion Architecture": "Anyın Arkitekçır",
    "domain driven design": "Domeyn Drivın Dizayn",
    "Domain Driven Design": "Domeyn Drivın Dizayn",
    "ddd": "Di Di Di",
    "DDD": "Di Di Di",
    "cqrs": "Si Kyu Ar Es",
    "CQRS": "Si Kyu Ar Es",
    "event sourcing": "İvent Sorsing",
    "Event Sourcing": "İvent Sorsing",
    "saga pattern": "Saga Patırn",
    "Saga Pattern": "Saga Patırn",
    "repository pattern": "Repozitori Patırn",
    "Repository Pattern": "Repozitori Patırn",
    "unit of work": "Yunit Ov Vörk",
    "Unit of Work": "Yunit Ov Vörk",
    "dependency injection": "Dipendınsi İncekşın",
    "Dependency Injection": "Dipendınsi İncekşın",
    "di": "Di Ay",
    "DI": "Di Ay",
    "ioc": "Ay Ov Si",
    "IoC": "Ay Ov Si",
    "inversion of control": "İnvörsın Ov Kontrol",
    "Inversion of Control": "İnvörsın Ov Kontrol",
    "service locator": "Sörvis Lokeytır",
    "Service Locator": "Sörvis Lokeytır",
    "aspect oriented": "Espekt Oriyentıd",
    "Aspect Oriented": "Espekt Oriyentıd",
    "aop": "Ey Ov Pi",
    "AOP": "Ey Ov Pi",
    "functional programming": "Fankşınıl Programming",
    "Functional Programming": "Fankşınıl Programming",
    "object oriented": "Obcekt Oriyentıd",
    "Object Oriented": "Obcekt Oriyentıd",
    "oop": "Ov Ov Pi",
    "OOP": "Ov Ov Pi",
    "procedural": "Prosicırıl",
    "Procedural": "Prosicırıl",
    "declarative": "Deklırıtiv",
    "Declarative": "Deklırıtiv",
    "imperative": "İmperıtiv",
    "Imperative": "İmperıtiv",
    "immutable": "İmyutıbıl",
    "Immutable": "İmyutıbıl",
    "mutable": "Myutıbıl",
    "Mutable": "Myutıbıl",
    "pure function": "Pyur Fankşın",
    "Pure Function": "Pyur Fankşın",
    "side effect": "Sayd İfekt",
    "Side Effect": "Sayd İfekt",
    "higher order function": "Hayır Ordır Fankşın",
    "Higher Order Function": "Hayır Ordır Fankşın",
    "closure": "Klojır",
    "Closure": "Klojır",
    "lambda": "Lemdı",
    "Lambda": "Lemdı",
    "map reduce filter": "Mep Ridüs Filtır",
    "monad": "Monad",
    "Monad": "Monad",
    "functor": "Fanktır",
    "Functor": "Fanktır",
    "recursion": "Rikörsın",
    "Recursion": "Rikörsın",
    "recursive": "Rikörsiv",
    "Recursive": "Rikörsiv",
    "tail recursion": "Teyl Rikörsın",
    "Tail Recursion": "Teyl Rikörsın",
    "memoization": "Memoyizeyşın",
    "Memoization": "Memoyizeyşın",
    "lazy evaluation": "Leyzi İvalyueyşın",
    "Lazy Evaluation": "Leyzi İvalyueyşın",
    "eager evaluation": "İgır İvalyueyşın",
    "Eager Evaluation": "İgır İvalyueyşın",
    "currying": "Köriying",
    "Currying": "Köriying",
    "partial application": "Parşıl Aplikeyşın",
    "Partial Application": "Parşıl Aplikeyşın",
    "composition": "Kompozişın",
    "Composition": "Kompozişın",
    "pipe": "Payp",
    "Pipe": "Payp",
    
    # ============================================
    # TEST & KALİTE
    # ============================================
    "unit test": "Yunit Test",
    "Unit Test": "Yunit Test",
    "unit testing": "Yunit Testing",
    "Unit Testing": "Yunit Testing",
    "integration test": "İntegreyşın Test",
    "Integration Test": "İntegreyşın Test",
    "integration testing": "İntegreyşın Testing",
    "Integration Testing": "İntegreyşın Testing",
    "end to end": "End Tu End",
    "End to End": "End Tu End",
    "e2e": "İ Tu İ",
    "E2E": "İ Tu İ",
    "e2e testing": "İ Tu İ Testing",
    "E2E Testing": "İ Tu İ Testing",
    "functional testing": "Fankşınıl Testing",
    "Functional Testing": "Fankşınıl Testing",
    "regression testing": "Regresyın Testing",
    "Regression Testing": "Regresyın Testing",
    "smoke testing": "Smok Testing",
    "Smoke Testing": "Smok Testing",
    "sanity testing": "Seniti Testing",
    "Sanity Testing": "Seniti Testing",
    "load testing": "Lod Testing",
    "Load Testing": "Lod Testing",
    "stress testing": "Stres Testing",
    "Stress Testing": "Stres Testing",
    "performance testing": "Pörformıns Testing",
    "Performance Testing": "Pörformıns Testing",
    "security testing": "Sekyuriti Testing",
    "Security Testing": "Sekyuriti Testing",
    "penetration testing": "Penetreyşın Testing",
    "Penetration Testing": "Penetreyşın Testing",
    "pen testing": "Pen Testing",
    "Pen Testing": "Pen Testing",
    "test driven development": "Test Drivın Divelopmınt",
    "Test Driven Development": "Test Drivın Divelopmınt",
    "tdd": "Ti Di Di",
    "TDD": "Ti Di Di",
    "behavior driven development": "Biheyviır Drivın Divelopmınt",
    "Behavior Driven Development": "Biheyviır Drivın Divelopmınt",
    "bdd": "Bi Di Di",
    "BDD": "Bi Di Di",
    "mock": "Mak",
    "Mock": "Mak",
    "mocking": "Making",
    "Mocking": "Making",
    "stub": "Stab",
    "Stub": "Stab",
    "spy": "Spay",
    "Spy": "Spay",
    "fake": "Feyk",
    "Fake": "Feyk",
    "fixture": "Fiksçır",
    "Fixture": "Fiksçır",
    "assertion": "Asörsın",
    "Assertion": "Asörsın",
    "expect": "Ekspekt",
    "Expect": "Ekspekt",
    "should": "Şud",
    "Should": "Şud",
    "describe": "Diskrayb",
    "Describe": "Diskrayb",
    "it": "İt",
    "It": "İt",
    "beforeeach": "Bifor İç",
    "BeforeEach": "Bifor İç",
    "aftereach": "Aftır İç",
    "AfterEach": "Aftır İç",
    "setup": "Setap",
    "Setup": "Setap",
    "teardown": "Tirdavn",
    "Teardown": "Tirdavn",
    "jest": "Cest",
    "Jest": "Cest",
    "mocha": "Moka",
    "Mocha": "Moka",
    "chai": "Çay",
    "Chai": "Çay",
    "jasmine": "Cesmin",
    "Jasmine": "Cesmin",
    "karma": "Karma",
    "Karma": "Karma",
    "cypress": "Saypres",
    "Cypress": "Saypres",
    "playwright": "Pleyvrayt",
    "Playwright": "Pleyvrayt",
    "selenium": "Seleniyum",
    "Selenium": "Seleniyum",
    "webdriver": "Veb Drayvır",
    "WebDriver": "Veb Drayvır",
    "puppeteer": "Papitir",
    "Puppeteer": "Papitir",
    "pytest": "Pay Test",
    "Pytest": "Pay Test",
    "unittest": "Yunit Test",
    "coverage": "Kavırıc",
    "Coverage": "Kavırıc",
    "code coverage": "Kod Kavırıc",
    "Code Coverage": "Kod Kavırıc",
    "sonarqube": "Sonar Kyub",
    "SonarQube": "Sonar Kyub",
    "sonar": "Sonar",
    "Sonar": "Sonar",
    "linter": "Lintır",
    "Linter": "Lintır",
    "linting": "Linting",
    "Linting": "Linting",
    "eslint": "İ Es Lint",
    "ESLint": "İ Es Lint",
    "prettier": "Pritiır",
    "Prettier": "Pritiır",
    "pylint": "Pay Lint",
    "Pylint": "Pay Lint",
    "flake8": "Fleyk Eyt",
    "Flake8": "Fleyk Eyt",
    "black": "Blek",
    "Black": "Blek",
    "mypy": "May Pay",
    "MyPy": "May Pay",
    "type hint": "Tayp Hint",
    "Type Hint": "Tayp Hint",
    "type hints": "Tayp Hints",
    "Type Hints": "Tayp Hints",
    "static analysis": "Stetik Enalisis",
    "Static Analysis": "Stetik Enalisis",
    "code smell": "Kod Smel",
    "Code Smell": "Kod Smel",
    "technical debt": "Teknikıl Det",
    "Technical Debt": "Teknikıl Det",
    "tech debt": "Tek Det",
    "Tech Debt": "Tek Det",
    
    # ============================================
    # DEVOPS & CLOUD
    # ============================================
    "infrastructure as code": "İnfrastrukçır Es Kod",
    "Infrastructure as Code": "İnfrastrukçır Es Kod",
    "iac": "Ay Ey Si",
    "IaC": "Ay Ey Si",
    "terraform": "Terraforım",
    "Terraform": "Terraforım",
    "ansible": "Ensibıl",
    "Ansible": "Ensibıl",
    "puppet": "Papit",
    "Puppet": "Papit",
    "chef": "Şef",
    "Chef": "Şef",
    "saltstack": "Salt Stek",
    "SaltStack": "Salt Stek",
    "cloudformation": "Klavd Formeyşın",
    "CloudFormation": "Klavd Formeyşın",
    "pulumi": "Pulumi",
    "Pulumi": "Pulumi",
    "helm": "Helm",
    "Helm": "Helm",
    "helm chart": "Helm Çart",
    "Helm Chart": "Helm Çart",
    "kustomize": "Kastımayz",
    "Kustomize": "Kastımayz",
    "argocd": "Argo Si Di",
    "ArgoCD": "Argo Si Di",
    "fluxcd": "Flaks Si Di",
    "FluxCD": "Flaks Si Di",
    "gitops": "Git Ops",
    "GitOps": "Git Ops",
    "service mesh": "Sörvis Meş",
    "Service Mesh": "Sörvis Meş",
    "istio": "İstiyo",
    "Istio": "İstiyo",
    "linkerd": "Linkırd",
    "Linkerd": "Linkırd",
    "consul": "Konsul",
    "Consul": "Konsul",
    "envoy": "Envoy",
    "Envoy": "Envoy",
    "sidecar": "Saydkar",
    "Sidecar": "Saydkar",
    "load balancer": "Lod Belınsır",
    "Load Balancer": "Lod Belınsır",
    "reverse proxy": "Rivörs Proksi",
    "Reverse Proxy": "Rivörs Proksi",
    "ingress": "İngres",
    "Ingress": "İngres",
    "egress": "İgres",
    "Egress": "İgres",
    "traefik": "Trefik",
    "Traefik": "Trefik",
    "haproxy": "Eyç Ey Proksi",
    "HAProxy": "Eyç Ey Proksi",
    "vpc": "Vi Pi Si",
    "VPC": "Vi Pi Si",
    "virtual private cloud": "Vörçuıl Prayvıt Klavd",
    "Virtual Private Cloud": "Vörçuıl Prayvıt Klavd",
    "subnet": "Sabnet",
    "Subnet": "Sabnet",
    "cidr": "Saydır",
    "CIDR": "Saydır",
    "nat": "Net",
    "NAT": "Net",
    "nat gateway": "Net Geytvey",
    "NAT Gateway": "Net Geytvey",
    "security group": "Sekyuriti Grup",
    "Security Group": "Sekyuriti Grup",
    "firewall": "Fayırvol",
    "Firewall": "Fayırvol",
    "waf": "Vef",
    "WAF": "Vef",
    "web application firewall": "Veb Aplikeyşın Fayırvol",
    "Web Application Firewall": "Veb Aplikeyşın Fayırvol",
    "cdn": "Si Di En",
    "CDN": "Si Di En",
    "content delivery network": "Kontınt Dilivıri Netvörk",
    "Content Delivery Network": "Kontınt Dilivıri Netvörk",
    "cloudflare": "Klavd Fler",
    "Cloudflare": "Klavd Fler",
    "akamai": "Akamai",
    "Akamai": "Akamai",
    "fastly": "Festli",
    "Fastly": "Festli",
    "ec2": "İ Si Tu",
    "EC2": "İ Si Tu",
    "s3": "Es Tri",
    "S3": "Es Tri",
    "lambda": "Lemdı",
    "Lambda": "Lemdı",
    "aws lambda": "Ey Dablyu Es Lemdı",
    "AWS Lambda": "Ey Dablyu Es Lemdı",
    "dynamodb": "Daynemo Di Bi",
    "DynamoDB": "Daynemo Di Bi",
    "rds": "Ar Di Es",
    "RDS": "Ar Di Es",
    "aurora": "Aurora",
    "Aurora": "Aurora",
    "redshift": "Redşift",
    "Redshift": "Redşift",
    "sqs": "Es Kyu Es",
    "SQS": "Es Kyu Es",
    "sns": "Es En Es",
    "SNS": "Es En Es",
    "kinesis": "Kinesis",
    "Kinesis": "Kinesis",
    "cloudwatch": "Klavd Voç",
    "CloudWatch": "Klavd Voç",
    "iam": "Ay Ey Em",
    "IAM": "Ay Ey Em",
    "eks": "İ Key Es",
    "EKS": "İ Key Es",
    "ecs": "İ Si Es",
    "ECS": "İ Si Es",
    "fargate": "Fargeyt",
    "Fargate": "Fargeyt",
    "elastic beanstalk": "İlestik Binstok",
    "Elastic Beanstalk": "İlestik Binstok",
    "sagemaker": "Seyc Meykır",
    "SageMaker": "Seyc Meykır",
    "azure functions": "Ejır Fankşıns",
    "Azure Functions": "Ejır Fankşıns",
    "azure devops": "Ejır Dev Ops",
    "Azure DevOps": "Ejır Dev Ops",
    "blob storage": "Blob Storic",
    "Blob Storage": "Blob Storic",
    "cosmos db": "Kozmos Di Bi",
    "Cosmos DB": "Kozmos Di Bi",
    "aks": "Ey Key Es",
    "AKS": "Ey Key Es",
    "google cloud functions": "Gugıl Klavd Fankşıns",
    "Google Cloud Functions": "Gugıl Klavd Fankşıns",
    "cloud run": "Klavd Ran",
    "Cloud Run": "Klavd Ran",
    "bigquery": "Big Kuiri",
    "BigQuery": "Big Kuiri",
    "dataflow": "Deytı Flov",
    "Dataflow": "Deytı Flov",
    "pub/sub": "Pab Sab",
    "Pub/Sub": "Pab Sab",
    "gke": "Ci Key İ",
    "GKE": "Ci Key İ",
    "vertex ai": "Vörteks Ey Ay",
    "Vertex AI": "Vörteks Ey Ay",
    "serverless": "Sörvırles",
    "Serverless": "Sörvırles",
    "faas": "Fas",
    "FaaS": "Fas",
    "function as a service": "Fankşın Es E Sörvis",
    "Function as a Service": "Fankşın Es E Sörvis",
    "paas": "Pas",
    "PaaS": "Pas",
    "platform as a service": "Pletform Es E Sörvis",
    "Platform as a Service": "Pletform Es E Sörvis",
    "iaas": "Ayas",
    "IaaS": "Ayas",
    "infrastructure as a service": "İnfrastrukçır Es E Sörvis",
    "Infrastructure as a Service": "İnfrastrukçır Es E Sörvis",
    "saas": "Sas",
    "SaaS": "Sas",
    "software as a service": "Softvır Es E Sörvis",
    "Software as a Service": "Softvır Es E Sörvis",
    "baas": "Bas",
    "BaaS": "Bas",
    "backend as a service": "Bek End Es E Sörvis",
    "Backend as a Service": "Bek End Es E Sörvis",
    "multi-cloud": "Malti Klavd",
    "Multi-Cloud": "Malti Klavd",
    "hybrid cloud": "Haybrid Klavd",
    "Hybrid Cloud": "Haybrid Klavd",
    "on-premise": "On Premis",
    "On-Premise": "On Premis",
    "on-prem": "On Prem",
    "On-Prem": "On Prem",
    "colocation": "Kolokeyşın",
    "Colocation": "Kolokeyşın",
    "data center": "Deytı Sentır",
    "Data Center": "Deytı Sentır",
    
    # ============================================
    # GÜVENLİK & KRİPTOGRAFİ
    # ============================================
    "cybersecurity": "Saybır Sekyuriti",
    "Cybersecurity": "Saybır Sekyuriti",
    "information security": "İnformeyşın Sekyuriti",
    "Information Security": "İnformeyşın Sekyuriti",
    "infosec": "İnfo Sek",
    "InfoSec": "İnfo Sek",
    "vulnerability": "Vulnırıbiliti",
    "Vulnerability": "Vulnırıbiliti",
    "vulnerabilities": "Vulnırıbilitis",
    "exploit": "Eksployt",
    "Exploit": "Eksployt",
    "payload": "Peylod",
    "Payload": "Peylod",
    "malware": "Melvır",
    "Malware": "Melvır",
    "ransomware": "Rensımvır",
    "Ransomware": "Rensımvır",
    "phishing": "Fişing",
    "Phishing": "Fişing",
    "spear phishing": "Spir Fişing",
    "Spear Phishing": "Spir Fişing",
    "social engineering": "Soşıl Enciinıring",
    "Social Engineering": "Soşıl Enciinıring",
    "brute force": "Brut Fors",
    "Brute Force": "Brut Fors",
    "dictionary attack": "Dikşıneri Atek",
    "Dictionary Attack": "Dikşıneri Atek",
    "rainbow table": "Reynbov Teybıl",
    "Rainbow Table": "Reynbov Teybıl",
    "sql injection": "Es Kyu El İncekşın",
    "SQL Injection": "Es Kyu El İncekşın",
    "xss": "Eks Es Es",
    "XSS": "Eks Es Es",
    "cross site scripting": "Kros Sayt Skripting",
    "Cross Site Scripting": "Kros Sayt Skripting",
    "csrf": "Si Es Ar Ef",
    "CSRF": "Si Es Ar Ef",
    "cross site request forgery": "Kros Sayt Rikuest Forcıri",
    "Cross Site Request Forgery": "Kros Sayt Rikuest Forcıri",
    "xxe": "Eks Eks İ",
    "XXE": "Eks Eks İ",
    "ssrf": "Es Es Ar Ef",
    "SSRF": "Es Es Ar Ef",
    "rce": "Ar Si İ",
    "RCE": "Ar Si İ",
    "remote code execution": "Rimot Kod Eksekuşın",
    "Remote Code Execution": "Rimot Kod Eksekuşın",
    "lfi": "El Ef Ay",
    "LFI": "El Ef Ay",
    "rfi": "Ar Ef Ay",
    "RFI": "Ar Ef Ay",
    "owasp": "Ovasp",
    "OWASP": "Ovasp",
    "cve": "Si Vi İ",
    "CVE": "Si Vi İ",
    "zero day": "Ziro Dey",
    "Zero Day": "Ziro Dey",
    "zero-day": "Ziro Dey",
    "encryption": "Enkripşın",
    "Encryption": "Enkripşın",
    "decryption": "Dikripşın",
    "Decryption": "Dikripşın",
    "symmetric": "Simetrik",
    "Symmetric": "Simetrik",
    "asymmetric": "Asimetrik",
    "Asymmetric": "Asimetrik",
    "aes": "Ey İ Es",
    "AES": "Ey İ Es",
    "rsa": "Ar Es Ey",
    "RSA": "Ar Es Ey",
    "sha": "Şa",
    "SHA": "Şa",
    "sha256": "Şa İki Yüz Elli Altı",
    "SHA256": "Şa İki Yüz Elli Altı",
    "sha512": "Şa Beş Yüz On İki",
    "SHA512": "Şa Beş Yüz On İki",
    "md5": "Em Di Fayv",
    "MD5": "Em Di Fayv",
    "bcrypt": "Bi Kript",
    "BCrypt": "Bi Kript",
    "argon2": "Argon Tu",
    "Argon2": "Argon Tu",
    "scrypt": "Es Kript",
    "SCrypt": "Es Kript",
    "pbkdf2": "Pi Bi Key Di Ef Tu",
    "PBKDF2": "Pi Bi Key Di Ef Tu",
    "hash": "Heş",
    "Hash": "Heş",
    "hashing": "Heşing",
    "Hashing": "Heşing",
    "salt": "Solt",
    "Salt": "Solt",
    "pepper": "Pepır",
    "Pepper": "Pepır",
    "digital signature": "Diciital Signıçır",
    "Digital Signature": "Diciital Signıçır",
    "certificate": "Sörtifikıt",
    "Certificate": "Sörtifikıt",
    "ssl": "Es Es El",
    "SSL": "Es Es El",
    "tls": "Ti El Es",
    "TLS": "Ti El Es",
    "https": "Eyç Ti Ti Pi Es",
    "HTTPS": "Eyç Ti Ti Pi Es",
    "public key": "Pablik Ki",
    "Public Key": "Pablik Ki",
    "private key": "Prayvıt Ki",
    "Private Key": "Prayvıt Ki",
    "key pair": "Ki Per",
    "Key Pair": "Ki Per",
    "pki": "Pi Key Ay",
    "PKI": "Pi Key Ay",
    "public key infrastructure": "Pablik Ki İnfrastrukçır",
    "Public Key Infrastructure": "Pablik Ki İnfrastrukçır",
    "ca": "Si Ey",
    "CA": "Si Ey",
    "certificate authority": "Sörtifikıt Atoriti",
    "Certificate Authority": "Sörtifikıt Atoriti",
    "jwt": "Cey Dablyu Ti",
    "JWT": "Cey Dablyu Ti",
    "json web token": "Ceysın Veb Tokın",
    "JSON Web Token": "Ceysın Veb Tokın",
    "oauth": "Ov Ot",
    "OAuth": "Ov Ot",
    "oauth2": "Ov Ot Tu",
    "OAuth2": "Ov Ot Tu",
    "openid": "Opın Ay Di",
    "OpenID": "Opın Ay Di",
    "openid connect": "Opın Ay Di Konekt",
    "OpenID Connect": "Opın Ay Di Konekt",
    "oidc": "Ov Ay Di Si",
    "OIDC": "Ov Ay Di Si",
    "saml": "Semıl",
    "SAML": "Semıl",
    "sso": "Es Es Ov",
    "SSO": "Es Es Ov",
    "single sign on": "Singıl Sayn On",
    "Single Sign On": "Singıl Sayn On",
    "mfa": "Em Ef Ey",
    "MFA": "Em Ef Ey",
    "multi factor authentication": "Malti Faktır Otentikeyşın",
    "Multi Factor Authentication": "Malti Faktır Otentikeyşın",
    "2fa": "Tu Ef Ey",
    "2FA": "Tu Ef Ey",
    "two factor authentication": "Tu Faktır Otentikeyşın",
    "Two Factor Authentication": "Tu Faktır Otentikeyşın",
    "totp": "Tot Pi",
    "TOTP": "Tot Pi",
    "hotp": "Hot Pi",
    "HOTP": "Hot Pi",
    "authentication": "Otentikeyşın",
    "Authentication": "Otentikeyşın",
    "authorization": "Otorizeyşın",
    "Authorization": "Otorizeyşın",
    "rbac": "Ar Bek",
    "RBAC": "Ar Bek",
    "role based access control": "Rol Beysd Ekses Kontrol",
    "Role Based Access Control": "Rol Beysd Ekses Kontrol",
    "abac": "Ey Bek",
    "ABAC": "Ey Bek",
    "attribute based access control": "Etribüt Beysd Ekses Kontrol",
    "Attribute Based Access Control": "Etribüt Beysd Ekses Kontrol",
    "acl": "Ey Si El",
    "ACL": "Ey Si El",
    "access control list": "Ekses Kontrol List",
    "Access Control List": "Ekses Kontrol List",
    "ldap": "El Dep",
    "LDAP": "El Dep",
    "active directory": "Ektiv Direktöri",
    "Active Directory": "Ektiv Direktöri",
    "kerberos": "Körbıros",
    "Kerberos": "Körbıros",
    "vault": "Volt",
    "Vault": "Volt",
    "hashicorp vault": "Haşikorp Volt",
    "HashiCorp Vault": "Haşikorp Volt",
    "secrets manager": "Sikrıts Menıcır",
    "Secrets Manager": "Sikrıts Menıcır",
    "key management": "Ki Menıcmınt",
    "Key Management": "Ki Menıcmınt",
    "kms": "Key Em Es",
    "KMS": "Key Em Es",
    "hsm": "Eyç Es Em",
    "HSM": "Eyç Es Em",
    "hardware security module": "Hardvır Sekyuriti Modül",
    "Hardware Security Module": "Hardvır Sekyuriti Modül",
    "siem": "Sim",
    "SIEM": "Sim",
    "security information and event management": "Sekyuriti İnformeyşın End İvent Menıcmınt",
    "soar": "Sor",
    "SOAR": "Sor",
    "ids": "Ay Di Es",
    "IDS": "Ay Di Es",
    "intrusion detection system": "İntrujın Detekşın Sistım",
    "Intrusion Detection System": "İntrujın Detekşın Sistım",
    "ips": "Ay Pi Es",
    "IPS": "Ay Pi Es",
    "intrusion prevention system": "İntrujın Privençın Sistım",
    "Intrusion Prevention System": "İntrujın Privençın Sistım",
    "dlp": "Di El Pi",
    "DLP": "Di El Pi",
    "data loss prevention": "Deytı Los Privençın",
    "Data Loss Prevention": "Deytı Los Privençın",
    "edr": "İ Di Ar",
    "EDR": "İ Di Ar",
    "endpoint detection and response": "Endpoynt Detekşın End Rispons",
    "Endpoint Detection and Response": "Endpoynt Detekşın End Rispons",
    "xdr": "Eks Di Ar",
    "XDR": "Eks Di Ar",
    "ndr": "En Di Ar",
    "NDR": "En Di Ar",
    "threat hunting": "Tret Hanting",
    "Threat Hunting": "Tret Hanting",
    "threat intelligence": "Tret İntelicıns",
    "Threat Intelligence": "Tret İntelicıns",
    "ioc": "Ay Ov Si",
    "IoC": "Ay Ov Si",
    "indicator of compromise": "İndikeytır Ov Kompromays",
    "Indicator of Compromise": "İndikeytır Ov Kompromays",
    "ttp": "Ti Ti Pi",
    "TTP": "Ti Ti Pi",
    "mitre att&ck": "Maytır Atek",
    "MITRE ATT&CK": "Maytır Atek",
    "red team": "Red Tim",
    "Red Team": "Red Tim",
    "blue team": "Blu Tim",
    "Blue Team": "Blu Tim",
    "purple team": "Pörpıl Tim",
    "Purple Team": "Pörpıl Tim",
    "bug bounty": "Bag Bavnti",
    "Bug Bounty": "Bag Bavnti",
    "responsible disclosure": "Risponsibıl Disklojır",
    "Responsible Disclosure": "Risponsibıl Disklojır",
    "compliance": "Komplayıns",
    "Compliance": "Komplayıns",
    "gdpr": "Ci Di Pi Ar",
    "GDPR": "Ci Di Pi Ar",
    "hipaa": "Hipa",
    "HIPAA": "Hipa",
    "pci dss": "Pi Si Ay Di Es Es",
    "PCI DSS": "Pi Si Ay Di Es Es",
    "soc2": "Sok Tu",
    "SOC2": "Sok Tu",
    "iso 27001": "Ayso Yirmi Yedi Bin Bir",
    "ISO 27001": "Ayso Yirmi Yedi Bin Bir",
    
    # ============================================
    # WEB GELİŞTİRME & FRONTEND
    # ============================================
    "html": "Eyç Ti Em El",
    "HTML": "Eyç Ti Em El",
    "html5": "Eyç Ti Em El Fayv",
    "HTML5": "Eyç Ti Em El Fayv",
    "css": "Si Es Es",
    "CSS": "Si Es Es",
    "css3": "Si Es Es Tri",
    "CSS3": "Si Es Es Tri",
    "sass": "Ses",
    "SASS": "Ses",
    "scss": "Es Si Es Es",
    "SCSS": "Es Si Es Es",
    "less": "Les",
    "LESS": "Les",
    "tailwind": "Teylvind",
    "Tailwind": "Teylvind",
    "tailwindcss": "Teylvind Si Es Es",
    "TailwindCSS": "Teylvind Si Es Es",
    "bootstrap": "But Strep",
    "Bootstrap": "But Strep",
    "material ui": "Matıriyıl Yu Ay",
    "Material UI": "Matıriyıl Yu Ay",
    "mui": "Em Yu Ay",
    "MUI": "Em Yu Ay",
    "chakra ui": "Çakra Yu Ay",
    "Chakra UI": "Çakra Yu Ay",
    "ant design": "Ent Dizayn",
    "Ant Design": "Ent Dizayn",
    "styled components": "Stayld Kompınınts",
    "Styled Components": "Stayld Kompınınts",
    "emotion": "İmoşın",
    "Emotion": "İmoşın",
    "css in js": "Si Es Es İn Cey Es",
    "CSS in JS": "Si Es Es İn Cey Es",
    "css modules": "Si Es Es Modüls",
    "CSS Modules": "Si Es Es Modüls",
    "flexbox": "Fleks Boks",
    "Flexbox": "Fleks Boks",
    "grid": "Grid",
    "Grid": "Grid",
    "css grid": "Si Es Es Grid",
    "CSS Grid": "Si Es Es Grid",
    "responsive": "Risponsiv",
    "Responsive": "Risponsiv",
    "responsive design": "Risponsiv Dizayn",
    "Responsive Design": "Risponsiv Dizayn",
    "media query": "Midya Kuiri",
    "Media Query": "Midya Kuiri",
    "breakpoint": "Breykpoynt",
    "Breakpoint": "Breykpoynt",
    "viewport": "Vyuport",
    "Viewport": "Vyuport",
    "mobile first": "Mobayıl Först",
    "Mobile First": "Mobayıl Först",
    "progressive web app": "Progresiv Veb Ep",
    "Progressive Web App": "Progresiv Veb Ep",
    "pwa": "Pi Dablyu Ey",
    "PWA": "Pi Dablyu Ey",
    "service worker": "Sörvis Vörkır",
    "Service Worker": "Sörvis Vörkır",
    "manifest": "Menifest",
    "Manifest": "Menifest",
    "web worker": "Veb Vörkır",
    "Web Worker": "Veb Vörkır",
    "indexeddb": "İndeksıd Di Bi",
    "IndexedDB": "İndeksıd Di Bi",
    "local storage": "Lokıl Storic",
    "Local Storage": "Lokıl Storic",
    "session storage": "Seşın Storic",
    "Session Storage": "Seşın Storic",
    "cookie": "Kuki",
    "Cookie": "Kuki",
    "cookies": "Kukis",
    "Cookies": "Kukis",
    "dom": "Dom",
    "DOM": "Dom",
    "document object model": "Dakümınt Obcekt Modıl",
    "Document Object Model": "Dakümınt Obcekt Modıl",
    "virtual dom": "Vörçuıl Dom",
    "Virtual DOM": "Vörçuıl Dom",
    "shadow dom": "Şedo Dom",
    "Shadow DOM": "Şedo Dom",
    "web component": "Veb Kompınınt",
    "Web Component": "Veb Kompınınt",
    "custom element": "Kastım Elimınt",
    "Custom Element": "Kastım Elimınt",
    "jsx": "Cey Es Eks",
    "JSX": "Cey Es Eks",
    "tsx": "Ti Es Eks",
    "TSX": "Ti Es Eks",
    "babel": "Beybıl",
    "Babel": "Beybıl",
    "webpack": "Veb Pek",
    "Webpack": "Veb Pek",
    "vite": "Vit",
    "Vite": "Vit",
    "rollup": "Rolap",
    "Rollup": "Rolap",
    "parcel": "Parsıl",
    "Parcel": "Parsıl",
    "esbuild": "İ Es Bild",
    "ESBuild": "İ Es Bild",
    "swc": "Es Dablyu Si",
    "SWC": "Es Dablyu Si",
    "turbopack": "Törbo Pek",
    "Turbopack": "Törbo Pek",
    "bundler": "Bandlır",
    "Bundler": "Bandlır",
    "bundling": "Bandling",
    "Bundling": "Bandling",
    "minification": "Minifikeyşın",
    "Minification": "Minifikeyşın",
    "uglify": "Aglifay",
    "Uglify": "Aglifay",
    "tree shaking": "Tri Şeyking",
    "Tree Shaking": "Tri Şeyking",
    "code splitting": "Kod Spliting",
    "Code Splitting": "Kod Spliting",
    "lazy loading": "Leyzi Loding",
    "Lazy Loading": "Leyzi Loding",
    "hydration": "Haydreyşın",
    "Hydration": "Haydreyşın",
    "server side rendering": "Sörvır Sayd Rendıring",
    "Server Side Rendering": "Sörvır Sayd Rendıring",
    "ssr": "Es Es Ar",
    "SSR": "Es Es Ar",
    "static site generation": "Stetik Sayt Cenerayşın",
    "Static Site Generation": "Stetik Sayt Cenerayşın",
    "ssg": "Es Es Ci",
    "SSG": "Es Es Ci",
    "incremental static regeneration": "İnkremıntıl Stetik Ricenerayşın",
    "isr": "Ay Es Ar",
    "ISR": "Ay Es Ar",
    "client side rendering": "Klayınt Sayd Rendıring",
    "Client Side Rendering": "Klayınt Sayd Rendıring",
    "csr": "Si Es Ar",
    "CSR": "Si Es Ar",
    "single page application": "Singıl Peyc Aplikeyşın",
    "Single Page Application": "Singıl Peyc Aplikeyşın",
    "spa": "Es Pi Ey",
    "SPA": "Es Pi Ey",
    "multi page application": "Malti Peyc Aplikeyşın",
    "Multi Page Application": "Malti Peyc Aplikeyşın",
    "mpa": "Em Pi Ey",
    "MPA": "Em Pi Ey",
    "astro": "Astro",
    "Astro": "Astro",
    "remix": "Rimiks",
    "Remix": "Rimiks",
    "svelte": "Svelt",
    "Svelte": "Svelt",
    "sveltekit": "Svelt Kit",
    "SvelteKit": "Svelt Kit",
    "nuxt": "Nakst",
    "Nuxt": "Nakst",
    "nuxtjs": "Nakst Cey Es",
    "Nuxt.js": "Nakst Cey Es",
    "gatsby": "Getsbi",
    "Gatsby": "Getsbi",
    "qwik": "Kuik",
    "Qwik": "Kuik",
    "solid.js": "Solid Cey Es",
    "SolidJS": "Solid Cey Es",
    "preact": "Priekt",
    "Preact": "Priekt",
    "alpine.js": "Alpayn Cey Es",
    "Alpine.js": "Alpayn Cey Es",
    "htmx": "Eyç Ti Em Eks",
    "HTMX": "Eyç Ti Em Eks",
    "hotwire": "Hat Vayır",
    "Hotwire": "Hat Vayır",
    "turbo": "Törbo",
    "Turbo": "Törbo",
    "stimulus": "Stimülıs",
    "Stimulus": "Stimülıs",
    "livewire": "Layv Vayır",
    "Livewire": "Layv Vayır",
    "inertia": "İnörşa",
    "Inertia": "İnörşa",
    "state management": "Steyt Menıcmınt",
    "State Management": "Steyt Menıcmınt",
    "redux": "Ridaks",
    "Redux": "Ridaks",
    "redux toolkit": "Ridaks Tulkit",
    "Redux Toolkit": "Ridaks Tulkit",
    "zustand": "Zustand",
    "Zustand": "Zustand",
    "jotai": "Cotay",
    "Jotai": "Cotay",
    "recoil": "Rikoyl",
    "Recoil": "Rikoyl",
    "mobx": "Mob Eks",
    "MobX": "Mob Eks",
    "pinia": "Pinya",
    "Pinia": "Pinya",
    "vuex": "Vyu Eks",
    "Vuex": "Vyu Eks",
    "ngrx": "En Ci Ar Eks",
    "NgRx": "En Ci Ar Eks",
    "signals": "Signıls",
    "Signals": "Signıls",
    "rxjs": "Ar Eks Cey Es",
    "RxJS": "Ar Eks Cey Es",
    "observable": "Obsörvıbıl",
    "Observable": "Obsörvıbıl",
    "observables": "Obsörvıbıls",
    "react query": "Riyekt Kuiri",
    "React Query": "Riyekt Kuiri",
    "tanstack query": "Ten Stek Kuiri",
    "TanStack Query": "Ten Stek Kuiri",
    "swr": "Es Dablyu Ar",
    "SWR": "Es Dablyu Ar",
    "trpc": "Ti Ar Pi Si",
    "tRPC": "Ti Ar Pi Si",
    "apollo": "Apolo",
    "Apollo": "Apolo",
    "apollo client": "Apolo Klayınt",
    "Apollo Client": "Apolo Klayınt",
    "urql": "Örkıl",
    "URQL": "Örkıl",
    "relay": "Riley",
    "Relay": "Riley",
    "fetch": "Feç",
    "Fetch": "Feç",
    "fetch api": "Feç Ey Pi Ay",
    "Fetch API": "Feç Ey Pi Ay",
    "axios": "Eksiyos",
    "Axios": "Eksiyos",
    "ky": "Kay",
    "Ky": "Kay",
    "got": "Gat",
    "Got": "Gat",
    "superagent": "Süpır Eycınt",
    "SuperAgent": "Süpır Eycınt",
    
    # ============================================
    # MOBİL GELİŞTİRME
    # ============================================
    "react native": "Riyekt Neytiv",
    "React Native": "Riyekt Neytiv",
    "flutter": "Flatır",
    "Flutter": "Flatır",
    "dart": "Dart",
    "Dart": "Dart",
    "expo": "Ekspo",
    "Expo": "Ekspo",
    "ionic": "Ayonik",
    "Ionic": "Ayonik",
    "capacitor": "Kepasitır",
    "Capacitor": "Kepasitır",
    "cordova": "Kordova",
    "Cordova": "Kordova",
    "xamarin": "Zemerin",
    "Xamarin": "Zemerin",
    "maui": "Mavi",
    "MAUI": "Mavi",
    ".net maui": "Dat Net Mavi",
    ".NET MAUI": "Dat Net Mavi",
    "swiftui": "Svift Yu Ay",
    "SwiftUI": "Svift Yu Ay",
    "uikit": "Yu Ay Kit",
    "UIKit": "Yu Ay Kit",
    "jetpack compose": "Cet Pek Kompoz",
    "Jetpack Compose": "Cet Pek Kompoz",
    "compose": "Kompoz",
    "Compose": "Kompoz",
    "android studio": "Endroyd Studyo",
    "Android Studio": "Endroyd Studyo",
    "xcode": "Eks Kod",
    "Xcode": "Eks Kod",
    "cocoapods": "Koko Pods",
    "CocoaPods": "Koko Pods",
    "gradle": "Greydıl",
    "Gradle": "Greydıl",
    "fastlane": "Fest Leyn",
    "Fastlane": "Fest Leyn",
    "testflight": "Test Flayt",
    "TestFlight": "Test Flayt",
    "app store": "Ep Stor",
    "App Store": "Ep Stor",
    "play store": "Pley Stor",
    "Play Store": "Pley Stor",
    "google play": "Gugıl Pley",
    "Google Play": "Gugıl Pley",
    "apk": "Ey Pi Key",
    "APK": "Ey Pi Key",
    "aab": "Ey Ey Bi",
    "AAB": "Ey Ey Bi",
    "ipa": "Ay Pi Ey",
    "IPA": "Ay Pi Ey",
    "push notification": "Puş Notifikeyşın",
    "Push Notification": "Puş Notifikeyşın",
    "firebase": "Fayır Beys",
    "Firebase": "Fayır Beys",
    "fcm": "Ef Si Em",
    "FCM": "Ef Si Em",
    "firebase cloud messaging": "Fayır Beys Klavd Mesicing",
    "apns": "Ey Pi En Es",
    "APNS": "Ey Pi En Es",
    "apple push notification": "Epıl Puş Notifikeyşın",
    "deep linking": "Dip Linking",
    "Deep Linking": "Dip Linking",
    "universal links": "Yünivörsıl Links",
    "Universal Links": "Yünivörsıl Links",
    "app links": "Ep Links",
    "App Links": "Ep Links",
    "biometric": "Bayometrik",
    "Biometric": "Bayometrik",
    "face id": "Feys Ay Di",
    "Face ID": "Feys Ay Di",
    "touch id": "Taç Ay Di",
    "Touch ID": "Taç Ay Di",
    "keychain": "Ki Çeyn",
    "Keychain": "Ki Çeyn",
    "keystore": "Ki Stor",
    "Keystore": "Ki Stor",
    "in-app purchase": "İn Ep Pörçıs",
    "In-App Purchase": "İn Ep Pörçıs",
    "iap": "Ay Ey Pi",
    "IAP": "Ay Ey Pi",
    "admob": "Ed Mob",
    "AdMob": "Ed Mob",
    "analytics": "Enalitiks",
    "Analytics": "Enalitiks",
    "crashlytics": "Kreşlitiks",
    "Crashlytics": "Kreşlitiks",
    "performance monitoring": "Pörformıns Manitıring",
    "Performance Monitoring": "Pörformıns Manitıring",
    "remote config": "Rimot Konfig",
    "Remote Config": "Rimot Konfig",
    "a/b test": "Ey Bi Test",
    "A/B Test": "Ey Bi Test",
    "feature flag": "Fiçır Fleg",
    "Feature Flag": "Fiçır Fleg",
    "feature flags": "Fiçır Flegs",
    "Feature Flags": "Fiçır Flegs",
    "feature toggle": "Fiçır Togıl",
    "Feature Toggle": "Fiçır Togıl",
    
    # ============================================
    # VERİTABANI & DEPOLAMA
    # ============================================
    "nosql": "No Es Kyu El",
    "NoSQL": "No Es Kyu El",
    "document database": "Dakümınt Deytıbeys",
    "Document Database": "Dakümınt Deytıbeys",
    "key value": "Ki Velyu",
    "Key Value": "Ki Velyu",
    "key-value store": "Ki Velyu Stor",
    "Key-Value Store": "Ki Velyu Stor",
    "column family": "Kolum Femili",
    "Column Family": "Kolum Femili",
    "graph database": "Graf Deytıbeys",
    "Graph Database": "Graf Deytıbeys",
    "time series": "Taym Siris",
    "Time Series": "Taym Siris",
    "time series database": "Taym Siris Deytıbeys",
    "cassandra": "Kesendra",
    "Cassandra": "Kesendra",
    "apache cassandra": "Epaçi Kesendra",
    "Apache Cassandra": "Epaçi Kesendra",
    "couchdb": "Kavç Di Bi",
    "CouchDB": "Kavç Di Bi",
    "couchbase": "Kavç Beys",
    "Couchbase": "Kavç Beys",
    "neo4j": "Niyo For Cey",
    "Neo4j": "Niyo For Cey",
    "dgraph": "Di Graf",
    "Dgraph": "Di Graf",
    "janusgraph": "Canüs Graf",
    "JanusGraph": "Canüs Graf",
    "neptune": "Neptün",
    "Neptune": "Neptün",
    "influxdb": "İnflaks Di Bi",
    "InfluxDB": "İnflaks Di Bi",
    "timescaledb": "Taym Skeyl Di Bi",
    "TimescaleDB": "Taym Skeyl Di Bi",
    "prometheus": "Prometiyus",
    "Prometheus": "Prometiyus",
    "grafana": "Grafana",
    "Grafana": "Grafana",
    "clickhouse": "Klik Havs",
    "ClickHouse": "Klik Havs",
    "druid": "Druıd",
    "Druid": "Druıd",
    "pinot": "Pino",
    "Pinot": "Pino",
    "sqlite": "Es Kyu Layt",
    "SQLite": "Es Kyu Layt",
    "mariadb": "Mariya Di Bi",
    "MariaDB": "Mariya Di Bi",
    "cockroachdb": "Kokroç Di Bi",
    "CockroachDB": "Kokroç Di Bi",
    "tidb": "Ti Di Bi",
    "TiDB": "Ti Di Bi",
    "yugabytedb": "Yuga Bayt Di Bi",
    "YugabyteDB": "Yuga Bayt Di Bi",
    "vitess": "Vites",
    "Vitess": "Vites",
    "planetscale": "Plenıt Skeyl",
    "PlanetScale": "Plenıt Skeyl",
    "supabase": "Süpıbeys",
    "Supabase": "Süpıbeys",
    "neon": "Nion",
    "Neon": "Nion",
    "prisma": "Prizma",
    "Prisma": "Prizma",
    "drizzle": "Drizıl",
    "Drizzle": "Drizıl",
    "typeorm": "Tayp Orm",
    "TypeORM": "Tayp Orm",
    "sequelize": "Sikuılayz",
    "Sequelize": "Sikuılayz",
    "sqlalchemy": "Es Kyu El Elkımi",
    "SQLAlchemy": "Es Kyu El Elkımi",
    "hibernate": "Haybırneyt",
    "Hibernate": "Haybırneyt",
    "jpa": "Cey Pi Ey",
    "JPA": "Cey Pi Ey",
    "entity framework": "Entiti Freymvörk",
    "Entity Framework": "Entiti Freymvörk",
    "dapper": "Depır",
    "Dapper": "Depır",
    "orm": "Ov Ar Em",
    "ORM": "Ov Ar Em",
    "object relational mapping": "Obcekt Rileyşınıl Meping",
    "Object Relational Mapping": "Obcekt Rileyşınıl Meping",
    "odm": "Ov Di Em",
    "ODM": "Ov Di Em",
    "object document mapper": "Obcekt Dakümınt Mepır",
    "mongoose": "Mongus",
    "Mongoose": "Mongus",
    "migration": "Mayreyşın",
    "Migration": "Mayreyşın",
    "migrations": "Mayreyşıns",
    "schema": "Skima",
    "Schema": "Skima",
    "index": "İndeks",
    "Index": "İndeks",
    "indexes": "İndeksiz",
    "indexing": "İndeksing",
    "Indexing": "İndeksing",
    "primary key": "Praymeri Ki",
    "Primary Key": "Praymeri Ki",
    "foreign key": "Foren Ki",
    "Foreign Key": "Foren Ki",
    "composite key": "Kompozit Ki",
    "Composite Key": "Kompozit Ki",
    "unique constraint": "Yunik Konstreynt",
    "Unique Constraint": "Yunik Konstreynt",
    "check constraint": "Çek Konstreynt",
    "Check Constraint": "Çek Konstreynt",
    "join": "Coyn",
    "Join": "Coyn",
    "inner join": "İnır Coyn",
    "Inner Join": "İnır Coyn",
    "left join": "Left Coyn",
    "Left Join": "Left Coyn",
    "right join": "Rayt Coyn",
    "Right Join": "Rayt Coyn",
    "outer join": "Avtır Coyn",
    "Outer Join": "Avtır Coyn",
    "cross join": "Kros Coyn",
    "Cross Join": "Kros Coyn",
    "subquery": "Sab Kuiri",
    "Subquery": "Sab Kuiri",
    "cte": "Si Ti İ",
    "CTE": "Si Ti İ",
    "common table expression": "Kamın Teybıl Ekspresyın",
    "Common Table Expression": "Kamın Teybıl Ekspresyın",
    "window function": "Vindov Fankşın",
    "Window Function": "Vindov Fankşın",
    "stored procedure": "Stord Prosicır",
    "Stored Procedure": "Stord Prosicır",
    "trigger": "Trigır",
    "Trigger": "Trigır",
    "view": "Vyu",
    "View": "Vyu",
    "materialized view": "Matiriyalazd Vyu",
    "Materialized View": "Matiriyalazd Vyu",
    "transaction": "Transekşın",
    "Transaction": "Transekşın",
    "acid": "Esid",
    "ACID": "Esid",
    "atomicity": "Atomisiti",
    "consistency": "Konsistensi",
    "isolation": "Ayzoleyşın",
    "durability": "Durıbiliti",
    "deadlock": "Dedlok",
    "Deadlock": "Dedlok",
    "lock": "Lok",
    "Lock": "Lok",
    "locking": "Loking",
    "Locking": "Loking",
    "optimistic locking": "Optimistik Loking",
    "Optimistic Locking": "Optimistik Loking",
    "pessimistic locking": "Pesimistik Loking",
    "Pessimistic Locking": "Pesimistik Loking",
    "sharding": "Şarding",
    "Sharding": "Şarding",
    "shard": "Şard",
    "Shard": "Şard",
    "replication": "Replikeyşın",
    "Replication": "Replikeyşın",
    "replica": "Replikı",
    "Replica": "Replikı",
    "master slave": "Mastır Sleyv",
    "Master Slave": "Mastır Sleyv",
    "primary secondary": "Praymeri Sekınderi",
    "Primary Secondary": "Praymeri Sekınderi",
    "read replica": "Rid Replikı",
    "Read Replica": "Rid Replikı",
    "write ahead log": "Rayt Ehed Log",
    "Write Ahead Log": "Rayt Ehed Log",
    "wal": "Vol",
    "WAL": "Vol",
    "binlog": "Bin Log",
    "Binlog": "Bin Log",
    "backup": "Bekap",
    "Backup": "Bekap",
    "restore": "Ristor",
    "Restore": "Ristor",
    "point in time recovery": "Poynt İn Taym Rikovıri",
    "pitr": "Pi Ay Ti Ar",
    "PITR": "Pi Ay Ti Ar",
    "disaster recovery": "Dizastır Rikovıri",
    "Disaster Recovery": "Dizastır Rikovıri",
    "dr": "Di Ar",
    "DR": "Di Ar",
    "high availability": "Hay Eveylıbiliti",
    "High Availability": "Hay Eveylıbiliti",
    "ha": "Eyç Ey",
    "HA": "Eyç Ey",
    "failover": "Feyl Ovır",
    "Failover": "Feyl Ovır",
    "connection pool": "Konekşın Pul",
    "Connection Pool": "Konekşın Pul",
    "connection pooling": "Konekşın Puling",
    "Connection Pooling": "Konekşın Puling",
    "pgbouncer": "Pi Ci Bavnsır",
    "PgBouncer": "Pi Ci Bavnsır",
    "query optimizer": "Kuiri Optimayzır",
    "Query Optimizer": "Kuiri Optimayzır",
    "execution plan": "Eksekuşın Plen",
    "Execution Plan": "Eksekuşın Plen",
    "explain": "Ekspleyn",
    "EXPLAIN": "Ekspleyn",
    "explain analyze": "Ekspleyn Enayz",
    "EXPLAIN ANALYZE": "Ekspleyn Enayz",
    
    # ============================================
    # AĞ & PROTOKOLLER
    # ============================================
    "tcp": "Ti Si Pi",
    "TCP": "Ti Si Pi",
    "udp": "Yu Di Pi",
    "UDP": "Yu Di Pi",
    "ip": "Ay Pi",
    "IP": "Ay Pi",
    "ipv4": "Ay Pi Vi For",
    "IPv4": "Ay Pi Vi For",
    "ipv6": "Ay Pi Vi Siks",
    "IPv6": "Ay Pi Vi Siks",
    "http": "Eyç Ti Ti Pi",
    "HTTP": "Eyç Ti Ti Pi",
    "http/2": "Eyç Ti Ti Pi Tu",
    "HTTP/2": "Eyç Ti Ti Pi Tu",
    "http/3": "Eyç Ti Ti Pi Tri",
    "HTTP/3": "Eyç Ti Ti Pi Tri",
    "quic": "Kuik",
    "QUIC": "Kuik",
    "grpc": "Ci Ar Pi Si",
    "gRPC": "Ci Ar Pi Si",
    "protobuf": "Proto Baf",
    "Protobuf": "Proto Baf",
    "protocol buffers": "Protokol Bafırs",
    "Protocol Buffers": "Protokol Bafırs",
    "thrift": "Trift",
    "Thrift": "Trift",
    "avro": "Evro",
    "Avro": "Evro",
    "json": "Ceysın",
    "JSON": "Ceysın",
    "xml": "Eks Em El",
    "XML": "Eks Em El",
    "yaml": "Yeml",
    "YAML": "Yeml",
    "toml": "Toml",
    "TOML": "Toml",
    "dns": "Di En Es",
    "DNS": "Di En Es",
    "domain name system": "Domeyn Neym Sistım",
    "Domain Name System": "Domeyn Neym Sistım",
    "dhcp": "Di Eyç Si Pi",
    "DHCP": "Di Eyç Si Pi",
    "arp": "Arp",
    "ARP": "Arp",
    "icmp": "Ay Si Em Pi",
    "ICMP": "Ay Si Em Pi",
    "ping": "Ping",
    "Ping": "Ping",
    "traceroute": "Treys Rut",
    "Traceroute": "Treys Rut",
    "ssh": "Es Es Eyç",
    "SSH": "Es Es Eyç",
    "sftp": "Es Ef Ti Pi",
    "SFTP": "Es Ef Ti Pi",
    "ftp": "Ef Ti Pi",
    "FTP": "Ef Ti Pi",
    "scp": "Es Si Pi",
    "SCP": "Es Si Pi",
    "rsync": "Ar Sink",
    "Rsync": "Ar Sink",
    "smtp": "Es Em Ti Pi",
    "SMTP": "Es Em Ti Pi",
    "imap": "Ay Mep",
    "IMAP": "Ay Mep",
    "pop3": "Pop Tri",
    "POP3": "Pop Tri",
    "mqtt": "Em Kyu Ti Ti",
    "MQTT": "Em Kyu Ti Ti",
    "amqp": "Ey Em Kyu Pi",
    "AMQP": "Ey Em Kyu Pi",
    "rabbitmq": "Rebit Em Kyu",
    "RabbitMQ": "Rebit Em Kyu",
    "zeromq": "Ziro Em Kyu",
    "ZeroMQ": "Ziro Em Kyu",
    "nats": "Nets",
    "NATS": "Nets",
    "socket": "Soket",
    "Socket": "Soket",
    "web socket": "Veb Soket",
    "WebSocket": "Veb Soket",
    "socket.io": "Soket Ay Ov",
    "Socket.IO": "Soket Ay Ov",
    "long polling": "Long Poling",
    "Long Polling": "Long Poling",
    "server sent events": "Sörvır Sent İvents",
    "Server Sent Events": "Sörvır Sent İvents",
    "sse": "Es Es İ",
    "SSE": "Es Es İ",
    "polling": "Poling",
    "Polling": "Poling",
    "webhook": "Veb Huk",
    "Webhook": "Veb Huk",
    "webhooks": "Veb Huks",
    "Webhooks": "Veb Huks",
    "cors": "Kors",
    "CORS": "Kors",
    "cross origin resource sharing": "Kros Oricin Risors Şering",
    "Cross Origin Resource Sharing": "Kros Oricin Risors Şering",
    "csp": "Si Es Pi",
    "CSP": "Si Es Pi",
    "content security policy": "Kontınt Sekyuriti Polisi",
    "Content Security Policy": "Kontınt Sekyuriti Polisi",
    "hsts": "Eyç Es Ti Es",
    "HSTS": "Eyç Es Ti Es",
    "http strict transport security": "Eyç Ti Ti Pi Strikt Transport Sekyuriti",
    "rate limiting": "Reyt Limiting",
    "Rate Limiting": "Reyt Limiting",
    "throttling": "Trotling",
    "Throttling": "Trotling",
    "circuit breaker": "Sörkıt Breykır",
    "Circuit Breaker": "Sörkıt Breykır",
    "retry": "Ritray",
    "Retry": "Ritray",
    "retry pattern": "Ritray Patırn",
    "Retry Pattern": "Ritray Patırn",
    "exponential backoff": "Eksponınşıl Bekof",
    "Exponential Backoff": "Eksponınşıl Bekof",
    "jitter": "Citır",
    "Jitter": "Citır",
    "timeout": "Taym Avt",
    "Timeout": "Taym Avt",
    "connection timeout": "Konekşın Taym Avt",
    "read timeout": "Rid Taym Avt",
    "write timeout": "Rayt Taym Avt",
    "keepalive": "Kip Elayv",
    "Keep-Alive": "Kip Elayv",
    "heartbeat": "Hart Bit",
    "Heartbeat": "Hart Bit",
    "health check": "Helt Çek",
    "Health Check": "Helt Çek",
    "liveness probe": "Layvnes Prob",
    "Liveness Probe": "Layvnes Prob",
    "readiness probe": "Redines Prob",
    "Readiness Probe": "Redines Prob",
    
    # ============================================
    # BLOCKCHAIN & WEB3
    # ============================================
    "blockchain": "Blokçeyn",
    "Blockchain": "Blokçeyn",
    "cryptocurrency": "Kripto Karınsi",
    "Cryptocurrency": "Kripto Karınsi",
    "bitcoin": "Bitkoyn",
    "Bitcoin": "Bitkoyn",
    "ethereum": "İtiriyum",
    "Ethereum": "İtiriyum",
    "solana": "Solana",
    "Solana": "Solana",
    "polygon": "Poligon",
    "Polygon": "Poligon",
    "avalanche": "Evalenç",
    "Avalanche": "Evalenç",
    "cardano": "Kardano",
    "Cardano": "Kardano",
    "polkadot": "Polkadot",
    "Polkadot": "Polkadot",
    "cosmos": "Kozmos",
    "Cosmos": "Kozmos",
    "arbitrum": "Arbitrım",
    "Arbitrum": "Arbitrım",
    "optimism": "Optimizm",
    "Optimism": "Optimizm",
    "layer 2": "Leyr Tu",
    "Layer 2": "Leyr Tu",
    "l2": "El Tu",
    "L2": "El Tu",
    "rollup": "Rolap",
    "Rollup": "Rolap",
    "zk rollup": "Zi Key Rolap",
    "ZK Rollup": "Zi Key Rolap",
    "optimistic rollup": "Optimistik Rolap",
    "Optimistic Rollup": "Optimistik Rolap",
    "smart contract": "Smart Kontrekt",
    "Smart Contract": "Smart Kontrekt",
    "solidity": "Soliditi",
    "Solidity": "Soliditi",
    "vyper": "Vaypır",
    "Vyper": "Vaypır",
    "rust": "Rast",
    "Rust": "Rast",
    "evm": "İ Vi Em",
    "EVM": "İ Vi Em",
    "ethereum virtual machine": "İtiriyum Vörçuıl Meşin",
    "gas": "Gas",
    "Gas": "Gas",
    "gas fee": "Gas Fi",
    "Gas Fee": "Gas Fi",
    "wei": "Vey",
    "Wei": "Vey",
    "gwei": "Gi Vey",
    "Gwei": "Gi Vey",
    "nft": "En Ef Ti",
    "NFT": "En Ef Ti",
    "non fungible token": "Non Fancıbıl Tokın",
    "Non Fungible Token": "Non Fancıbıl Tokın",
    "defi": "Di Fay",
    "DeFi": "Di Fay",
    "decentralized finance": "Disentralazd Faynens",
    "Decentralized Finance": "Disentralazd Faynens",
    "dex": "Deks",
    "DEX": "Deks",
    "decentralized exchange": "Disentralazd Eksçeync",
    "Decentralized Exchange": "Disentralazd Eksçeync",
    "cex": "Seks",
    "CEX": "Seks",
    "centralized exchange": "Sentralazd Eksçeync",
    "Centralized Exchange": "Sentralazd Eksçeync",
    "uniswap": "Yuni Svap",
    "Uniswap": "Yuni Svap",
    "pancakeswap": "Penkeyk Svap",
    "PancakeSwap": "Penkeyk Svap",
    "aave": "Eyv",
    "Aave": "Eyv",
    "compound": "Kompavnd",
    "Compound": "Kompavnd",
    "liquidity pool": "Likuiditi Pul",
    "Liquidity Pool": "Likuiditi Pul",
    "yield farming": "Yild Farming",
    "Yield Farming": "Yild Farming",
    "staking": "Steyking",
    "Staking": "Steyking",
    "proof of work": "Pruf Ov Vörk",
    "Proof of Work": "Pruf Ov Vörk",
    "pow": "Pav",
    "PoW": "Pav",
    "proof of stake": "Pruf Ov Steyk",
    "Proof of Stake": "Pruf Ov Steyk",
    "pos": "Pos",
    "PoS": "Pos",
    "consensus": "Konsensıs",
    "Consensus": "Konsensıs",
    "mining": "Mayning",
    "Mining": "Mayning",
    "miner": "Maynır",
    "Miner": "Maynır",
    "validator": "Validatır",
    "Validator": "Validatır",
    "node": "Nod",
    "Node": "Nod",
    "full node": "Ful Nod",
    "Full Node": "Ful Nod",
    "light node": "Layt Nod",
    "Light Node": "Layt Nod",
    "wallet": "Volet",
    "Wallet": "Volet",
    "metamask": "Meta Mesk",
    "MetaMask": "Meta Mesk",
    "ledger": "Lecır",
    "Ledger": "Lecır",
    "trezor": "Trezor",
    "Trezor": "Trezor",
    "cold wallet": "Kold Volet",
    "Cold Wallet": "Kold Volet",
    "hot wallet": "Hat Volet",
    "Hot Wallet": "Hat Volet",
    "seed phrase": "Sid Freyz",
    "Seed Phrase": "Sid Freyz",
    "mnemonic": "Nimonik",
    "Mnemonic": "Nimonik",
    "private key": "Prayvıt Ki",
    "public address": "Pablik Edres",
    "Public Address": "Pablik Edres",
    "dao": "Dav",
    "DAO": "Dav",
    "decentralized autonomous organization": "Disentralazd Atonımıs Organizeyşın",
    "governance": "Gavırnıns",
    "Governance": "Gavırnıns",
    "voting": "Voting",
    "Voting": "Voting",
    "proposal": "Propozıl",
    "Proposal": "Propozıl",
    "web3": "Veb Tri",
    "Web3": "Veb Tri",
    "dapp": "Di Ep",
    "DApp": "Di Ep",
    "decentralized application": "Disentralazd Aplikeyşın",
    "Decentralized Application": "Disentralazd Aplikeyşın",
    "ipfs": "Ay Pi Ef Es",
    "IPFS": "Ay Pi Ef Es",
    "interplanetary file system": "İntırplenıteri Fayl Sistım",
    "filecoin": "Fayl Koyn",
    "Filecoin": "Fayl Koyn",
    "arweave": "Ar Viv",
    "Arweave": "Ar Viv",
    "ens": "İ En Es",
    "ENS": "İ En Es",
    "ethereum name service": "İtiriyum Neym Sörvis",
    "hardhat": "Hard Het",
    "Hardhat": "Hard Het",
    "truffle": "Trafl",
    "Truffle": "Trafl",
    "foundry": "Favndri",
    "Foundry": "Favndri",
    "remix": "Rimiks",
    "Remix": "Rimiks",
    "ethers.js": "İtırs Cey Es",
    "Ethers.js": "İtırs Cey Es",
    "web3.js": "Veb Tri Cey Es",
    "Web3.js": "Veb Tri Cey Es",
    "wagmi": "Vagmi",
    "Wagmi": "Vagmi",
    "viem": "Viyem",
    "Viem": "Viyem",
    "alchemy": "Elkımi",
    "Alchemy": "Elkımi",
    "infura": "İnfura",
    "Infura": "İnfura",
    "quicknode": "Kuik Nod",
    "QuickNode": "Kuik Nod",
    "chainlink": "Çeyn Link",
    "Chainlink": "Çeyn Link",
    "oracle": "Orakıl",
    "Oracle": "Orakıl",
    "bridge": "Bric",
    "Bridge": "Bric",
    "cross chain": "Kros Çeyn",
    "Cross Chain": "Kros Çeyn",
    "interoperability": "İntıroperıbiliti",
    "Interoperability": "İntıroperıbiliti",
    
    # ============================================
    # ROBOTİK & GÖMÜLÜ SİSTEMLER
    # ============================================
    "robotics": "Robotiks",
    "Robotics": "Robotiks",
    "ros": "Ros",
    "ROS": "Ros",
    "robot operating system": "Robot Opereyting Sistım",
    "Robot Operating System": "Robot Opereyting Sistım",
    "ros2": "Ros Tu",
    "ROS2": "Ros Tu",
    "gazebo": "Gezibo",
    "Gazebo": "Gezibo",
    "rviz": "Ar Viz",
    "RViz": "Ar Viz",
    "moveit": "Muv İt",
    "MoveIt": "Muv İt",
    "navigation": "Nevigeşın",
    "Navigation": "Nevigeşın",
    "localization": "Lokalizeyşın",
    "Localization": "Lokalizeyşın",
    "mapping": "Meping",
    "Mapping": "Meping",
    "path planning": "Pet Plening",
    "Path Planning": "Pet Plening",
    "motion planning": "Moşın Plening",
    "Motion Planning": "Moşın Plening",
    "kinematics": "Kinematiks",
    "Kinematics": "Kinematiks",
    "inverse kinematics": "İnvörs Kinematiks",
    "Inverse Kinematics": "İnvörs Kinematiks",
    "forward kinematics": "Forvırd Kinematiks",
    "Forward Kinematics": "Forvırd Kinematiks",
    "dynamics": "Daynamiks",
    "Dynamics": "Daynamiks",
    "actuator": "Ekçuyeytır",
    "Actuator": "Ekçuyeytır",
    "servo": "Sörvo",
    "Servo": "Sörvo",
    "stepper motor": "Stepır Motır",
    "Stepper Motor": "Stepır Motır",
    "dc motor": "Di Si Motır",
    "DC Motor": "Di Si Motır",
    "encoder": "Enkodır",
    "Encoder": "Enkodır",
    "sensor fusion": "Sensır Fyujın",
    "Sensor Fusion": "Sensır Fyujın",
    "imu": "Ay Em Yu",
    "IMU": "Ay Em Yu",
    "inertial measurement unit": "İnörşıl Mejırmınt Yunit",
    "accelerometer": "Ekselıromitır",
    "Accelerometer": "Ekselıromitır",
    "gyroscope": "Cayröskop",
    "Gyroscope": "Cayröskop",
    "magnetometer": "Megnitomitır",
    "Magnetometer": "Megnitomitır",
    "gps": "Ci Pi Es",
    "GPS": "Ci Pi Es",
    "gnss": "Ci En Es Es",
    "GNSS": "Ci En Es Es",
    "ultrasonic": "Altrasonik",
    "Ultrasonic": "Altrasonik",
    "infrared": "İnfrıred",
    "Infrared": "İnfrıred",
    "proximity sensor": "Proksimiti Sensır",
    "Proximity Sensor": "Proksimiti Sensır",
    "embedded system": "Embedid Sistım",
    "Embedded System": "Embedid Sistım",
    "embedded systems": "Embedid Sistıms",
    "Embedded Systems": "Embedid Sistıms",
    "microcontroller": "Maykro Kontrolır",
    "Microcontroller": "Maykro Kontrolır",
    "mcu": "Em Si Yu",
    "MCU": "Em Si Yu",
    "arduino": "Arduıno",
    "Arduino": "Arduıno",
    "esp32": "İ Es Pi Otuz İki",
    "ESP32": "İ Es Pi Otuz İki",
    "esp8266": "İ Es Pi Seksen İki Altmış Altı",
    "stm32": "Es Ti Em Otuz İki",
    "STM32": "Es Ti Em Otuz İki",
    "pic": "Pik",
    "PIC": "Pik",
    "avr": "Ey Vi Ar",
    "AVR": "Ey Vi Ar",
    "fpga": "Ef Pi Ci Ey",
    "FPGA": "Ef Pi Ci Ey",
    "field programmable gate array": "Fild Programıbıl Geyt Erey",
    "asic": "Eysik",
    "ASIC": "Eysik",
    "application specific integrated circuit": "Aplikeyşın Spesifik İntıgreytıd Sörkıt",
    "vhdl": "Vi Eyç Di El",
    "VHDL": "Vi Eyç Di El",
    "verilog": "Verilog",
    "Verilog": "Verilog",
    "pcb": "Pi Si Bi",
    "PCB": "Pi Si Bi",
    "printed circuit board": "Printıd Sörkıt Bord",
    "Printed Circuit Board": "Printıd Sörkıt Bord",
    "schematic": "Skımetik",
    "Schematic": "Skımetik",
    "gpio": "Ci Pi Ay Ov",
    "GPIO": "Ci Pi Ay Ov",
    "general purpose input output": "Cenırıl Pörpıs İnput Avtput",
    "i2c": "Ay Tu Si",
    "I2C": "Ay Tu Si",
    "spi": "Es Pi Ay",
    "SPI": "Es Pi Ay",
    "uart": "Yu Art",
    "UART": "Yu Art",
    "can bus": "Ken Bas",
    "CAN Bus": "Ken Bas",
    "modbus": "Mod Bas",
    "Modbus": "Mod Bas",
    "pwm": "Pi Dablyu Em",
    "PWM": "Pi Dablyu Em",
    "pulse width modulation": "Pals Vidt Modüleyşın",
    "adc": "Ey Di Si",
    "ADC": "Ey Di Si",
    "analog to digital converter": "Analog Tu Diciital Konvörtır",
    "dac": "Dek",
    "DAC": "Dek",
    "digital to analog converter": "Diciital Tu Analog Konvörtır",
    "interrupt": "İntırapt",
    "Interrupt": "İntırapt",
    "timer": "Taymır",
    "Timer": "Taymır",
    "watchdog": "Voçdog",
    "Watchdog": "Voçdog",
    "bootloader": "But Lodır",
    "Bootloader": "But Lodır",
    "firmware": "Förmvır",
    "Firmware": "Förmvır",
    "ota": "Ov Ti Ey",
    "OTA": "Ov Ti Ey",
    "over the air": "Ovır Di Eyr",
    "Over The Air": "Ovır Di Eyr",
    "rtos": "Ar Ti Ov Es",
    "RTOS": "Ar Ti Ov Es",
    "real time operating system": "Riıl Taym Opereyting Sistım",
    "Real Time Operating System": "Riıl Taym Opereyting Sistım",
    "freertos": "Fri Ar Ti Ov Es",
    "FreeRTOS": "Fri Ar Ti Ov Es",
    "zephyr": "Zefir",
    "Zephyr": "Zefir",
    
    # ============================================
    # IoT (NESNELERİN İNTERNETİ)
    # ============================================
    "iot": "Ay Ov Ti",
    "IoT": "Ay Ov Ti",
    "internet of things": "İnternet Ov Tings",
    "Internet of Things": "İnternet Ov Tings",
    "iiot": "Ay Ay Ov Ti",
    "IIoT": "Ay Ay Ov Ti",
    "industrial iot": "İndastriıl Ay Ov Ti",
    "Industrial IoT": "İndastriıl Ay Ov Ti",
    "smart home": "Smart Hom",
    "Smart Home": "Smart Hom",
    "home automation": "Hom Otomeyşın",
    "Home Automation": "Hom Otomeyşın",
    "zigbee": "Zig Bi",
    "ZigBee": "Zig Bi",
    "z-wave": "Zi Veyv",
    "Z-Wave": "Zi Veyv",
    "bluetooth": "Blu Tut",
    "Bluetooth": "Blu Tut",
    "ble": "Bi El İ",
    "BLE": "Bi El İ",
    "bluetooth low energy": "Blu Tut Lov Enerci",
    "Bluetooth Low Energy": "Blu Tut Lov Enerci",
    "wifi": "Vay Fay",
    "WiFi": "Vay Fay",
    "wi-fi": "Vay Fay",
    "Wi-Fi": "Vay Fay",
    "lora": "Lora",
    "LoRa": "Lora",
    "lorawan": "Lora Ven",
    "LoRaWAN": "Lora Ven",
    "nb-iot": "En Bi Ay Ov Ti",
    "NB-IoT": "En Bi Ay Ov Ti",
    "narrowband iot": "Nerov Bend Ay Ov Ti",
    "lte-m": "El Ti İ Em",
    "LTE-M": "El Ti İ Em",
    "5g": "Fayv Ci",
    "5G": "Fayv Ci",
    "edge computing": "Ec Kompyuting",
    "Edge Computing": "Ec Kompyuting",
    "fog computing": "Fog Kompyuting",
    "Fog Computing": "Fog Kompyuting",
    "aws iot": "Ey Dablyu Es Ay Ov Ti",
    "AWS IoT": "Ey Dablyu Es Ay Ov Ti",
    "azure iot hub": "Ejır Ay Ov Ti Hab",
    "Azure IoT Hub": "Ejır Ay Ov Ti Hab",
    "google cloud iot": "Gugıl Klavd Ay Ov Ti",
    "Google Cloud IoT": "Gugıl Klavd Ay Ov Ti",
    "thingsboard": "Tings Bord",
    "ThingsBoard": "Tings Bord",
    "home assistant": "Hom Asistınt",
    "Home Assistant": "Hom Asistınt",
    "node-red": "Nod Red",
    "Node-RED": "Nod Red",
    "tasmota": "Tasmota",
    "Tasmota": "Tasmota",
    "esphome": "İ Es Pi Hom",
    "ESPHome": "İ Es Pi Hom",
    "matter": "Metır",
    "Matter": "Metır",
    "thread": "Tred",
    "Thread": "Tred",
    
    # ============================================
    # EK MÜHENDİSLİK TERİMLERİ
    # ============================================
    "agile methodology": "Ecayl Metodoloci",
    "Agile Methodology": "Ecayl Metodoloci",
    "waterfall": "Votırfol",
    "Waterfall": "Votırfol",
    "lean": "Lin",
    "Lean": "Lin",
    "six sigma": "Siks Sigma",
    "Six Sigma": "Siks Sigma",
    "devops": "Dev Ops",
    "DevOps": "Dev Ops",
    "devsecops": "Dev Sek Ops",
    "DevSecOps": "Dev Sek Ops",
    "sre": "Es Ar İ",
    "SRE": "Es Ar İ",
    "site reliability engineering": "Sayt Rilayabiliti Enciinıring",
    "Site Reliability Engineering": "Sayt Rilayabiliti Enciinıring",
    "sla": "Es El Ey",
    "SLA": "Es El Ey",
    "service level agreement": "Sörvis Level Egrımınt",
    "Service Level Agreement": "Sörvis Level Egrımınt",
    "slo": "Es El Ov",
    "SLO": "Es El Ov",
    "service level objective": "Sörvis Level Obcektiv",
    "Service Level Objective": "Sörvis Level Obcektiv",
    "sli": "Es El Ay",
    "SLI": "Es El Ay",
    "service level indicator": "Sörvis Level İndikeytır",
    "Service Level Indicator": "Sörvis Level İndikeytır",
    "uptime": "Ap Taym",
    "Uptime": "Ap Taym",
    "downtime": "Davn Taym",
    "Downtime": "Davn Taym",
    "mttr": "Em Ti Ti Ar",
    "MTTR": "Em Ti Ti Ar",
    "mean time to recovery": "Min Taym Tu Rikovıri",
    "Mean Time to Recovery": "Min Taym Tu Rikovıri",
    "mtbf": "Em Ti Bi Ef",
    "MTBF": "Em Ti Bi Ef",
    "mean time between failures": "Min Taym Bitvin Feyliırs",
    "Mean Time Between Failures": "Min Taym Bitvin Feyliırs",
    "incident": "İnsidınt",
    "Incident": "İnsidınt",
    "incident management": "İnsidınt Menıcmınt",
    "Incident Management": "İnsidınt Menıcmınt",
    "postmortem": "Post Mortım",
    "Postmortem": "Post Mortım",
    "root cause analysis": "Rut Koz Enalisis",
    "Root Cause Analysis": "Rut Koz Enalisis",
    "rca": "Ar Si Ey",
    "RCA": "Ar Si Ey",
    "blameless": "Bleymles",
    "Blameless": "Bleymles",
    "on-call": "On Kol",
    "On-Call": "On Kol",
    "pagerduty": "Peycır Dyuti",
    "PagerDuty": "Peycır Dyuti",
    "opsgenie": "Ops Cini",
    "OpsGenie": "Ops Cini",
    "victorops": "Viktor Ops",
    "VictorOps": "Viktor Ops",
    "runbook": "Ran Buk",
    "Runbook": "Ran Buk",
    "playbook": "Pley Buk",
    "Playbook": "Pley Buk",
    "observability": "Obsörvabiliti",
    "Observability": "Obsörvabiliti",
    "monitoring": "Manitıring",
    "Monitoring": "Manitıring",
    "logging": "Loging",
    "Logging": "Loging",
    "tracing": "Treysing",
    "Tracing": "Treysing",
    "distributed tracing": "Distribütıd Treysing",
    "Distributed Tracing": "Distribütıd Treysing",
    "jaeger": "Yegır",
    "Jaeger": "Yegır",
    "zipkin": "Zipkin",
    "Zipkin": "Zipkin",
    "opentelemetry": "Opın Telemetri",
    "OpenTelemetry": "Opın Telemetri",
    "otel": "Otel",
    "OTel": "Otel",
    "datadog": "Deytı Dog",
    "Datadog": "Deytı Dog",
    "new relic": "Nyu Relik",
    "New Relic": "Nyu Relik",
    "splunk": "Splank",
    "Splunk": "Splank",
    "elk stack": "Elk Stek",
    "ELK Stack": "Elk Stek",
    "elastic": "İlestik",
    "Elastic": "İlestik",
    "logstash": "Log Steş",
    "Logstash": "Log Steş",
    "kibana": "Kibana",
    "Kibana": "Kibana",
    "fluentd": "Fluınt Di",
    "Fluentd": "Fluınt Di",
    "fluent bit": "Fluınt Bit",
    "Fluent Bit": "Fluınt Bit",
    "loki": "Loki",
    "Loki": "Loki",
    "tempo": "Tempo",
    "Tempo": "Tempo",
    "mimir": "Mimir",
    "Mimir": "Mimir",
    "thanos": "Tanos",
    "Thanos": "Tanos",
    "cortex": "Korteks",
    "Cortex": "Korteks",
    "alertmanager": "Alert Menıcır",
    "AlertManager": "Alert Menıcır",
    "prom": "Prom",
    "promql": "Prom Kyu El",
    "PromQL": "Prom Kyu El",
    "metric": "Metrik",
    "Metric": "Metrik",
    "metrics": "Metriks",
    "Metrics": "Metriks",
    "counter": "Kavntır",
    "Counter": "Kavntır",
    "gauge": "Geyc",
    "Gauge": "Geyc",
    "histogram": "Histoğram",
    "summary": "Samıri",
    "Summary": "Samıri",
    "label": "Leybıl",
    "Label": "Leybıl",
    "labels": "Leybıls",
    "Labels": "Leybıls",
    "cardinality": "Kardinaliti",
    "Cardinality": "Kardinaliti",
    "retention": "Ritençın",
    "Retention": "Ritençın",
    "aggregation": "Egrıgeyşın",
    "Aggregation": "Egrıgeyşın",
    "downsampling": "Davn Sempling",
    "Downsampling": "Davn Sempling",
    "dashboard": "Deşbord",
    "Dashboard": "Deşbord",
    "visualization": "Vizuılizeyşın",
    "Visualization": "Vizuılizeyşın",
    "alert": "Alert",
    "Alert": "Alert",
    "alerting": "Alerting",
    "Alerting": "Alerting",
    "threshold": "Treşhold",
    "Threshold": "Treşhold",
    "anomaly detection": "Enomıli Detekşın",
    "Anomaly Detection": "Enomıli Detekşın",
}


def apply_pronunciation(text: str) -> str:
    """Teknik terimleri fonetik yazıma çevir."""
    result = text
    
    # Uzun terimlerden kısalara doğru sırala
    sorted_terms = sorted(PRONUNCIATION_DICT.keys(), key=len, reverse=True)
    
    for term in sorted_terms:
        # Kelime sınırlarını kontrol et
        pattern = r'\b' + re.escape(term) + r'\b'
        result = re.sub(pattern, PRONUNCIATION_DICT[term], result, flags=re.IGNORECASE)
    
    return result


class TTSService:
    """Text-to-Speech servisi."""
    
    def __init__(self):
        self.voices = VOICES
    
    async def generate_speech(
        self, 
        text: str, 
        voice_gender: str = "male",
        apply_tech_pronunciation: bool = True
    ) -> dict:
        """
        Metni sese çevir.
        
        Args:
            text: Okunacak metin
            voice_gender: "male" veya "female"
            apply_tech_pronunciation: Teknik terimleri fonetik yap
        
        Returns:
            {"audio_bytes": bytes, "success": True} veya
            {"error": "hata mesajı", "success": False}
        """
        try:
            # Ses seç
            voice = self.voices.get(voice_gender, self.voices["male"])
            
            # Teknik terimleri fonetik yap
            processed_text = text
            if apply_tech_pronunciation:
                processed_text = apply_pronunciation(text)
            
            # Geçici dosya oluştur
            temp_file = tempfile.NamedTemporaryFile(delete=False, suffix=".mp3")
            temp_path = temp_file.name
            temp_file.close()
            
            # Edge-TTS ile ses oluştur
            communicate = edge_tts.Communicate(processed_text, voice)
            await communicate.save(temp_path)
            
            # Dosyayı oku
            with open(temp_path, "rb") as f:
                audio_bytes = f.read()
            
            # Temizlik
            os.unlink(temp_path)
            
            return {
                "audio_bytes": audio_bytes,
                "original_text": text,
                "processed_text": processed_text,
                "voice": voice,
                "success": True
            }
            
        except Exception as e:
            return {
                "error": f"TTS hatası: {str(e)}",
                "success": False
            }
    
    def get_available_voices(self) -> dict:
        """Mevcut sesleri döndür."""
        return {
            "male": {"id": "tr-TR-AhmetNeural", "name": "Ahmet (Erkek)"},
            "female": {"id": "tr-TR-EmelNeural", "name": "Emel (Kadın)"},
        }


# Singleton instance
tts_service = TTSService()
